### ISSUE TITLE
Continuously clicking bottom navigation tabs leads to "java.lang.IllegalArgumentException" saveBackStack.....

### ISSUE THREAD

**Issue by kasem-sm** [android/architecture-components-samples#1006]
Issue with NavigationAdvancedSample

Version used: 2.4.0-alpha01 (used in sample) & 2.4.0-alpha03 (latest)
Devices/Android versions reproduced on: ALL

There would be a crash when pressing the bottom navigation icons continuously (like mad) and shifting between fragments (by pressing random nav icons).
(Log screenshot & screen recording attached)

https://user-images.githubusercontent.com/83884225/123041316-c84e3300-d412-11eb-813c-decffc95ed45.mp4

![Wed Jun 23 2021 10_53_21 GMT+0530 (India Standard Time)](https://user-images.githubusercontent.com/83884225/123041327-ca17f680-d412-11eb-8c0e-7cbfe228ed8c.png)

....
End

**Comment by esathamzaj** [comment]
Same here

**Comment by kasem-sm** [comment]
> Same here
https://issuetracker.google.com/issues/191791847

Checkout this

**Comment by abalta** [comment]
Same issue when multi touch all nav menus.

**Comment by ianhanniballake** [comment]
Yep, see [b/188896069](https://issuetracker.google.com/issues/188896069).
