### ISSUE TITLE
NavigationAdvancedSample appBarConfiguration not working after update to 2.4.0-alpha01

### ISSUE THREAD

**Issue by mw-intive** [android/architecture-components-samples#1007]
Hello,

When running the sample app I see weird behaviour of the back arrow appearing on the root screen of every tab

Android device: Huwaei P30 pro, android 11.0.0

![NavigationAdvancedSampleIssue](https://user-images.githubusercontent.com/58589172/123395119-20667000-d5a0-11eb-8f55-c87c9c26a952.png)

**Comment by ianhanniballake** [comment]
This was fixed in [b/189868637](https://issuetracker.google.com/issues/189868637) as part of [Navigation 2.4.0-alpha03](https://developer.android.com/jetpack/androidx/releases/navigation#2.4.0-alpha03) and will be picked up by the sample once we update the dependency.
