### ISSUE TITLE
[Navigation Advanced Sample 2.4.0-alpha10] Conflicting backstacks

### ISSUE THREAD

**Issue by ishaansrm** [android/architecture-components-samples#1031]
[Navigation Advanced Sample 2.4.0-alpha10]

Repro Steps:
1. Go to about section in home tab
2. switch to tab 2
3. press back -> home frag opens (intended behavior)
4. press home bottom tab (or go to tab 2 then press home tab) -> about frag opens

Observed Behavior:
Home frag opens different frags, depending on how the user reached there

Expected Behavior:
Once user presses back to reach home, home's backstack should be cleared, to avoid inconsistency in the screen that will be shown to a user

**Comment by ianhanniballake** [comment]
Dup of [b/188963883](https://issuetracker.google.com/issues/188963883).
