### ISSUE TITLE
PagingWithNetworkSample: After Paging 3 update, indexInResponse is now unused; Ordering behavior is unclear

### ISSUE THREAD

**Issue by aconda-mercari** [android/architecture-components-samples#1051]
I'm trying to understand how to keep the ordering from the backend into Room, and I noticed the variable `indexInResponse` was used for this exact use case. However, after the paging 3 migration in this codebase, this variable is now unused and returns 0 for all items, although it is still used in `ORDER BY` in the query.

I need to do exactly this so I want to know whether insertion order is preserved now in Paging 3 making `indexInResponse` unnecessary. From checking Room-generated I don't see anything like this happening, and as far as I know, SQLite doesn't guarantee this, otherwise, a variable like `indexInResponse` would not be necessary in the first place even for Paging 2.

Looking for clarification in this scenario, so comments around this are appreciated.

**Comment by claraf3** [comment]
Ordering is not guaranteed. With the sample app's current state where `indexInResponse` is no-op, PagingSource returns item based on insertion order. But again, this is not guaranteed. It is recommended you use `ORDER BY` on the query that returns the PagingSource to ensure same order across invalidations.

Sample app has been updated with an `ORDER BY` based statement.
