### ISSUE TITLE
Kotlin: Implemented methods with overrides not called correctly

### ISSUE THREAD

**Issue by JonLatane** [android/architecture-components-samples#138]
Hi! I'm using Room to implement local caching of remote data (by using a composite PK of (id, syncStatus) on all synchronized entities, but that's not super relevant).  To manage this, I'm having all my Daos implement the following (Kotlin) interface:

```
interface LocalDao<KeyType, EntityType: LocalRemoteEntity<KeyType, EntityType>> {
  @get:JvmSynthetic val db: RoomDatabase
  @JvmSynthetic fun loadAllCopies(id: KeyType): List<EntityType>
  @JvmSynthetic fun loadAll(): List<EntityType>
  @Insert(onConflict=REPLACE)
  fun upsert(entity: EntityType)
  @Delete
  fun delete(entity: EntityType)
}
```
My database looks like this:
```
@Database(
  version = 1,
  entities = arrayOf(
    Site::class
  )
)
abstract class SiteTestDatabase : RoomDatabase() {
  abstract val siteDao: SiteDao
}

@Dao
abstract class SiteDao(override val db: RoomDatabase): LocalDao<Int, Site> {
  @Query("SELECT * FROM site WHERE id = :arg0")
  override abstract fun loadAllCopies(arg0: Int): List<Site>
  @Query("SELECT * FROM site")
  override abstract fun loadAll(): List<Site>
}
```

With some test code:
```
val db = Room.inMemoryDatabaseBuilder(context, SiteTestDatabase::class.java).build()
// Add a site with ID = 1
val allSites = db.siteDao.loadAll() // works fine
val resultList = db.siteDao.loadAllCopies(1) // throws an InvocationTargetException
```

Both are calling to Room's generated `SiteDao_Impl` but it seems like the one with args isn't working properly somehow, even though `SiteDao_Impl` definitely has both load methods. I'm also still experiencing issues with argument name mangling, but I think these were in Kotlin and it does compile fine now (I'm on 1.1.4-2 and Room/Arch Alpha 9).

**Comment by mynote** [comment]
Since the code is generate by an annotation processor you shouldn't use Baseclasses / interfaces for the Daos. Same for TypeConverter.

**Comment by ianhanniballake** [comment]
This doesn't seem to be an issue with the samples. You can file an issue against Room on [the issue tracker](https://issuetracker.google.com/issues/new?component=413107) if you're still having an issue.
