### ISSUE TITLE
Parameter 'context' is not use in Basic Sample

### ISSUE THREAD

**Issue by ye-lin-aung** [android/architecture-components-samples#15]
The parameter context is not use in DatabaseCreator.java
<img width="612" alt="screen shot 2017-05-22 at 00 18 05" src="https://cloud.githubusercontent.com/assets/11737664/26286165/50185bc2-3e84-11e7-9f8e-6e6fc6a6fc26.png">

**Comment by ianhanniballake** [comment]
`DatabaseCreator` was removed entirely in #231
