### ISSUE TITLE
NetworkBoundResource and Paging library?

### ISSUE THREAD

**Issue by gajicm93** [android/architecture-components-samples#156]
We need a good sample how to combine these two? I don't think NetworkBoundSource can be properly used as a Mediator for Paged data?

**Comment by sreekanth-krishnan** [comment]
And please add samples in Java too

**Comment by shanuka** [comment]
yes please add java sample for paging

**Comment by cgpllx** [comment]
please add java sample for paging

**Comment by dlam** [comment]
Layered sources are now built into Paging3 via `RemoteMediator`! Java samples for LiveData / Rx / Guava are available on d.android.com/paging3!
