### ISSUE TITLE
Context leak

### ISSUE THREAD

**Issue by m6s** [android/architecture-components-samples#16]
https://github.com/googlesamples/android-architecture-components/blob/master/BasicSample/app/src/main/java/com/example/android/persistence/ProductFragment.java#L52

`mBinding = DataBindingUtil.inflate(inflater, R.layout.product_fragment, container, false);`

You store the binding into a field and never null it out. AFAIK this will leak the activity context.

**Comment by yigit** [comment]
this wont' really leak the activity since it already contains the fragment.
But it will leak the fragment's View's if the fragment is replaced & aded to back stack.

**Comment by yigit** [comment]
Jose,
we can either use the auto clear from the github demo or just return existing binding in onCreateView (if we want to keep the view around)

**Comment by ianhanniballake** [comment]
This was fixed in #785
