### ISSUE TITLE
Paging of only forward seekale data sources

### ISSUE THREAD

**Issue by mos8502** [android/architecture-components-samples#163]
It can been tricky but it would be nice to see a take on data sources that are only forward seekable. For example the github user api (unless I'm missing something) only allows forward seeking (paging), as the Link response headers don't have a prev link. As a page of suers can be fetched using the "since" parameter (user id) it would be a KeyedDataSource datasource but there is no way of loading users "before" a user id.

**Comment by dlam** [comment]
This is definitely supported now as passing `null` for `prevKey` terminates loading on the `PREPEND` side.
