### ISSUE TITLE
LifecycleRegistryOwner deprecated, recommended replacement.

### ISSUE THREAD

**Issue by andre-artus** [android/architecture-components-samples#170]
I've been busy doing a conversion of the sample app into Kotlin (the Java only ones) and as part of that conversion I've been updating the samples to the latest versions of the architecture components (`1.0.0-beta1` at this writing) and the support library (`26.1.0`).

`LifecycleRegistryOwner` has been deprecated, but neither the sample (the original `GithubBrowserSample` nor my conversion `GithubBrowserSampleKotlin`) will work if I just remove it. I suspect that it's a relatively simple matter to convert `RepoFragment` to work without it, but that goes against the spirit of the conversion (staying faithful to what been demonstrated in the original). 

What would be the recommended approach to getting rid of the deprecated `LifecycleRegistryOwner`? It's my understanding that the Fragments and Activities in the support libraries use `LifecycleRegistry` internally.

I've found it possible to get the fragment to work by removing the following (parts block commented out):

``` Kotlin
class RepoFragment : Fragment(), 
/* LifecycleRegistryOwner, */
Injectable {

/*
   private val lifecycleRegistry = LifecycleRegistry(this) 
*/

// ...

/*
   override fun getLifecycle(): LifecycleRegistry {
        return lifecycleRegistry
    }
*/
```

To see the code in context:
https://github.com/andre-artus/android-architecture-components/blob/734867e9f82f2658c13ff1ac9a5ef66f43be7b88/GithubBrowserSampleKotlin/app/src/main/java/com/android/example/github/ui/repo/RepoFragment.kt#L42

**Comment by mynote** [comment]
That works. Make sure you import the proper Fragment-Class `android.support.v4.app.Fragment.`

You dont need to use a LifecycleRegistry anymore since it's built into the support-library 26.1.0+
```
class RepoFragment : Fragment(), Injectable {
    @Inject lateinit var viewModelFactory: ViewModelProvider.Factory
}

```

Fragment class in support-lib:

`public class Fragment implements ComponentCallbacks, OnCreateContextMenuListener, LifecycleOwner
`

**Comment by andre-artus** [comment]
@mynote ,

Thanks, that's what I did, removed the "implements" and the implementation, and it works. Just seemed simpler than expected, so I needed to know if I'm missing something..
