### ISSUE TITLE
startActivity not working properly

### ISSUE THREAD

**Issue by ViramP** [android/architecture-components-samples#183]
Hello

I have used google codebase sample example.

When i tried to called new activity then new activity called more than twice.

```
public void onChanged(@Nullable Integer value) {
                if (value != null) {
                
                            Intent intent = new Intent(getActivity(),com.example.android.lifecycles.step5.Activity_step5.class);
                            startActivity(intent);

                }
            } 
```

**Comment by andre-artus** [comment]
@ViramP, do you have a more comprehensive example. What is onChanged activated by? Could be that it is fired twice.

**Comment by ViramP** [comment]
I have called on Login API and which **`setValue(status_code)`**.
So from onChanged i called StartActivity method.

Here not getting idea why onChanged called more than twice.
Here i need to do any extra effort for this ?

**Comment by andre-artus** [comment]
onChanged is a Lifecycle event. When you start the new activity you are also changing life-cycle state of the old one.

**Comment by ViramP** [comment]
Can you give details what need to do for that ?

**Comment by andre-artus** [comment]
I don;t think you should be starting new activities upon lifecycle changes, that can lead you down a rabbit hole.

**Comment by andre-artus** [comment]
Which example did you base it on?

**Comment by andre-artus** [comment]
ViramP, I'm sorry but I cannot determine from what you have shown so far what it is you are trying to achieve. If I had more information I would gladly help.

**Comment by ViramP** [comment]
I have used Google Codelabs example and add **StartActivity from my end**.

https://codelabs.developers.google.com/codelabs/android-persistence/#0

**Comment by ViramP** [comment]
@andre-artus 

My complete all flow should be like below:

Implement Basic Login Page with Web API calling.
On success of Login move to Home screen.
Home screen have another Web API which return some list.
I want to display that list with RecycleView.

**Comment by andre-artus** [comment]
Have you looked at the LoginActivity started app?

**Comment by ViramP** [comment]
not getting your question.

**Comment by andre-artus** [comment]
You are trying to stat a new activity on changes to the life cycle, that is not recommended. When you go to create a new activity in android Studio there is an option called "Login Activity" this serves as a good example of how to check the credentials off the UI thread, and taking a different course of action based on the result.

```
 protected void onPostExecute(final Boolean success)
```

**Comment by andre-artus** [comment]
You would of course replace the section between the ` // TODO: `  comments with your actual login check.

``` Java
        protected Boolean doInBackground(Void... params) {
            // TODO: attempt authentication against a network service. replace this block with your own code

            try {
                // Simulate network access.
                Thread.sleep(2000);
            } catch (InterruptedException e) {
                return false;
            }

            for (String credential : DUMMY_CREDENTIALS) {
                String[] pieces = credential.split(":");
                if (pieces[0].equals(mEmail)) {
                    // Account exists, return true if the password matches.
                    return pieces[1].equals(mPassword);
                }
            }

            // TODO: register the new account here.
            return true;
        }
```

**Comment by ViramP** [comment]
Yes
I have idea about of above Login Template of Android Activity.
But i want to Perform some action from OnChanged which called from LoginAPI success response.

Please find my complete code so you can get more idea for same.

LoginActivity:

```
 loginViewModel.loadIssues("20",password,uname,"51").observe
                            (LoginActivity.this,
                                    new Observer<ApiResponse>() {
                                        @Override
                                        public void onChanged(@Nullable ApiResponse apiResponse) {
                                            if(apiResponse.error != null){

                                            }else{
                                                Login login = apiResponse.login;
                                                login_progress.setVisibility(View.GONE);
                                                if(login.getData() != null){
                                                    Toast.makeText(LoginActivity.this,
                                                            ""+login.getData().getEmployeeEnglishName(), Toast.LENGTH_SHORT).show();
                                                }
                                               username.setText("");
                                               mPasswordView.setText("");
                                                startActivity(new Intent(LoginActivity.this,MainActivity.class));
                                            }

                                        }

                                    });
```

LoginViewModel:

   ```
 private MediatorLiveData<ApiResponse> mApiResponse;

public LiveData<ApiResponse> loadIssues(@NonNull String IMEI, String password,String username, String VersionCode) {
        mApiResponse.addSource(
                responseRepository.getLoginDetails(IMEI, password, username, VersionCode),
                new Observer<ApiResponse>() {
                    @Override
                    public void onChanged(@Nullable ApiResponse apiResponse) {
                        mApiResponse.postValue(apiResponse);

                    }
                }
        );
        return mApiResponse;
    }

```

Here,to achieve this functionality which changes need to do with above.

**Comment by andre-artus** [comment]
I'll look at it after work.

**Comment by ViramP** [comment]
Ok
Thanks

**Comment by andre-artus** [comment]
@ViramP , 
Sorry to take so long but my area has been plagued by power cuts necessitating that I spend the time I had available on my own projects.

Which sample did you base your project on? I've looked though all of them and I cannot find one that uses the libraries in the way you have done.  I've even looked through the "googlesamples/android-architecture" repository. In fact everything I've read would indicate to me that this is something you should not do.

The ViewModel and LiveData classes are there to keep your data and display (activity/fragment/view) in sync with each other, and I'm getting the idea that you are trying to use iot for background processing, when there are better ways of doing that.

If I had the following requirements:
1. A Login screen that initiates an online authentication check, and 
2. processes in the background, and
3. shows a progress/busy indicator. and
4. starts a new activity on success, OR
5. shows an error state and prompts the user to retry.

I would do this:
1. The authentication check would happen on a background worker/ async task.
2. The communication (and only that) between the login activity and the authentication check would be done via ViewModel+LiveData (e.g show progress, disable.enable views, etc.).
3. The authentication worker will be responsible for initiating any secondary activities (likely through a navigation controller).

**Comment by ianhanniballake** [comment]
While a useful conversation, this has nothing to do with the samples in this repository and this would be better suited as a StackOverflow question.
