### ISSUE TITLE
RoomProcessor shomehow hides the com.turbomanage.storm.apt.MainProcessor

### ISSUE THREAD

**Issue by vasimihalca** [android/architecture-components-samples#185]
Hello, 

I am trying to introduce Room on a project that has the db layer done with Storm Gen, a lib that died two years ago.
https://github.com/turbomanage/storm-gen
I cannot do a full migration because the project is too big so I would like to convert only the search/search results functionality of the app for now. 
I will have a separate database name only with the tables used by these screens. The rest of the tables are kinda independent from a database perspective. 
Once I add the lines below to my database class, it does not compile.
_@Database(entities = {
		MakeEntity.class
}, version = 1)
@TypeConverters(DateConverter.class)_ 

In the terminal, once it reaches the Javac task, first it throws a bunch of errors that it cannot see the storm files that should be generated. Then later in the logs the storm annotation processor kicks in and generates the classes.

If I comment out the @Database room annotation, the code runs fine..however room can't work. 

I need to make to be able to add Room along with StormGen, cause its the only feasible way we can introduce Room in this project.
If there are any other details I can provide, please let me know! :)

Thanks in advance!

**Comment by yigit** [comment]
javac has a problem where, if it hits an error, it ignores the code generated by processors.
Can you share the full gradle output, maybe there is a real error that gets lost in the list of errors about Storm.

**Comment by ianhanniballake** [comment]
Please file an issue against Room on [the issue tracker](https://issuetracker.google.com/issues/new?component=413107) if this is still an issue.
