### ISSUE TITLE
How to get user id after insert a user?

### ISSUE THREAD

**Issue by biswanathgit** [android/architecture-components-samples#210]
This is a question 
I am doing the rx-java sample.. on that I am trying to improve this..  where I need the user id after a new User is enrolled. 
So I did the following changes  : 

`  @Insert(onConflict = OnConflictStrategy.REPLACE)
    long insertUser(User user);`  //where user id is auto generate  

Actually I facing problem with  Competable insertUser Function 
` public Completable insertProduct(Product newProduct) {
        return new CompletableFromAction(() -> {
            mProductDataSource.insertOrUpdateProduct(newProduct);
      });
    }`

**Comment by jffiorillo** [comment]
What is the problem that you are facing ?

**Comment by ianhanniballake** [comment]
This doesn't seem to be an issue with the samples. You can file an issue against Room on [the issue tracker](https://issuetracker.google.com/issues/new?component=413107) if you're still having an issue.
