### ISSUE TITLE
new version android studio 3.0 can not run the module

### ISSUE THREAD

**Issue by zhoujingheng** [android/architecture-components-samples#219]
i update the version android studio 3.0 , when i import the GithubBrowserSample , the run button not enable

**Comment by a2213502** [comment]
the samethings to me , do you resloved this question?

**Comment by jimandreas** [comment]
Hi all - the `versions.gradle` file in the root of the repo cannot be seen by android studio when you open a subproject.   Here is what I have done as a workaround:

1) copy the `versions.gradle` file into the subproject, for example `GithubBrowserSample`.

2) edit the project's top level `build.gradle` file to import the `versions.gradle` file from the current directory.

```
      //    apply from: '../versions.gradle'
        apply from: 'versions.gradle'
```
3) update the `versions.gradle` line `versions.android_gradle_plugin = "3.0.0-something"` to your required version of the android gradle plugin (3.0.0 for the released version of Android Studio)

4) sync the project and build.   My first pass build had a dex error - which I solved by deleting the `./build` and `app/build` folders and building again.   Then the `GithubBrowserSample` built successfully and ran without errors.   The androidTests (connected tests) and the junit test suites also ran without errors.

**Comment by pedrofelipemm** [comment]
@jimandreas 
It works without steps 1 and 2 (at last for me). I just needed to fix the version.gradle.
Thanks for sharing!
