### ISSUE TITLE
How to use sqlite trigger on Room Persistence

### ISSUE THREAD

**Issue by crossle** [android/architecture-components-samples#221]
I use Room persistence , i wanna create a sqlite trigger update other table, how to create on Room persistence, or where i can create the trigger use sql

**Comment by VitaliPekelis** [comment]
https://stackoverflow.com/a/45633544/3289520

**Comment by ianhanniballake** [comment]
This doesn't seem to be an issue with the samples. You can file an issue against Room on [the issue tracker](https://issuetracker.google.com/issues/new?component=413107) if you have a feature request or question.
