### ISSUE TITLE
Could not resolve android.arch.core:core-testing:1.0.0-alpha1. Required by

### ISSUE THREAD

**Issue by chenycu** [android/architecture-components-samples#23]
When I build Project the following error：

>Failed to resolve: Could not resolve android.arch.core:core-testing:1.0.0-alpha1. Required by: project :app Open File

How to deal with it?

**Comment by JoseAlcerreca** [comment]
What project?

**Comment by JoseAlcerreca** [comment]
Is this a dup of #25 ?

**Comment by chenycu** [comment]
Not the reason for the network, I can download all the dependencies in the GithubBrowserSample project in addition to this one.I am using Android studio 3.0, also used the Http proxy.BasicSample can be compiled and run normally

**Comment by ianhanniballake** [comment]
Seems that everything is working now.
