### ISSUE TITLE
Paging library with network only datasource stuck after off/on internet connection

### ISSUE THREAD

**Issue by AucT** [android/architecture-components-samples#232]
Hi!
How to make paging library's TiledDataSource loadRange work again after off/on internet connection?

p.s. please, if you have time, make some example on paging through network datasource (in java plz).

**Comment by daimonkor** [comment]
Please provide example with progress loading view and catching errors (missing internet connection). How bind and unbind pagination?

**Comment by sahoosunilkumar** [comment]
I am facing same problem. any solution?

**Comment by yokrysty** [comment]
same here

**Comment by dlam** [comment]
Paging3 has added an API on `PagingDataAdapter` to `.retry()` errors.

**Comment by ghozimahdi** [comment]
> Paging3 has added an API on `PagingDataAdapter` to `.retry()` errors.

Hello, I tried the `.retry ()` API, but it doesn't work. i am using rxPagingSource

**Comment by dlam** [comment]
> Hello, I tried the `.retry ()` API, but it doesn't work. i am using rxPagingSource

Thanks for letting us know - if you're able to provide a repro and file a bug to our issue tracker, it would help a lot as well!

https://issuetracker.google.com/issues/new?component=413106&template=1096385

**Comment by dlam** [comment]
Also preemptively, make sure you notify presentation side of a recoverable error by catching the exception in `PagingSource` and returning `LoadResult.Error`.
