### ISSUE TITLE
AddSource not work - On Change not call

### ISSUE THREAD

**Issue by ShahakM** [android/architecture-components-samples#235]
Inside NetworkBoundResource when I add the dbSource to the result the 'onChange' method not call
Someone had the same problem? I try to figure it out for 3 days.
in other places it work and the code is the same like in the GitHub.

**Comment by abbenyyyyyy** [comment]
I have the same situation，in my case:the first time open the application without the network,then connect network and retry Repository access data method. 'loadFromDb' can not call the dbSource onChanged.

But when i am use ‘Transformations.switchMap()’ like 
[GithubBrowserSample Code](https://github.com/googlesamples/android-architecture-components/blob/1532c562bb4d25f8469471478195160fd96b5db7/GithubBrowserSample/app/src/main/java/com/android/example/github/ui/user/UserViewModel.java#L45), it can call the dbSource onChanged.

My WrongCode is direct use 'moviesRepository.getMovies(moveType)'.

My CorrectCode:

```
  LiveData<Resource<List<Movie>>> mObservableMovies;
  MutableLiveData<String> moveType = new MutableLiveData<>();
  mObservableMovies = Transformations.switchMap(moveType, new Function<String, LiveData<Resource<List<Movie>>>>() {
        @Override
        public LiveData<Resource<List<Movie>>> apply(String input) {
            if (input == null) {
                return AbsentLiveData.create();
            } else {
                return moviesRepository.getMovies(input);
            }
        }
     });
```

I hope my experience can help you.

**Comment by ShahakM** [comment]
It's not help. and also I don't understand why this can be the problem.
it's very strange only from NetworkBound the onChange not call.

**Comment by namdp** [comment]
as my experience MediatorLiveData -> addSource() not call if you don't observe the result. It's could be bug

**Comment by devqmr** [comment]
As @namdp  say you must result LiveData so addSource() called

**Comment by lingdianguole** [comment]
How do you solve the problem?it refuse me too

**Comment by WangChangQin** [comment]
@namdp  thanks you oh

**Comment by marinovskiy** [comment]
What should I do if I don't have any params, like in @abbenyyyyyy's answer? If I load data without any queries or paths?

**Comment by namdp** [comment]
You have to observe your LiveData from Activity/Fragment, if not
observe -> AddSource
not work

**Comment by marinovskiy** [comment]
@namdp do you mean that I should keep LiveData objects inside View (Activity, Fragment)? Could you, please, provide some example?

**Comment by marinovskiy** [comment]
@namdp could you, please, provide some example?

**Comment by namdp** [comment]
No, keep your LiveData in ViewModel, but you must observe it if you want
AddSource trigger
Check out google sample,
https://github.com/googlesamples/android-architecture-components/tree/master/GithubBrowserSample
- Ex: In "SearchViewModel" -> val results: LiveData<Resource<List<Repo>>>
you can see the results was observed in "SearchFragment"

searchViewModel.results.observe(...)

**Comment by marinovskiy** [comment]
@namdp so, the point in using Transformations (or MediatorLiveData if I have no queries or paths for loading data), right?

**Comment by ianhanniballake** [comment]
This doesn't seem to be an issue with the samples. You can file an issue against Lifecycle on [the issue tracker](https://issuetracker.google.com/issues/new?component=413132) if you're still having an issue.

**Comment by ZebdaYacine** [comment]
thank you it  is running very well
