### ISSUE TITLE
https://github.com/googlesamples/android-architecture-components.

### ISSUE THREAD

**Issue by hannesa2** [android/architecture-components-samples#237]
https://github.com/googlesamples/android-architecture-components/blob/1532c562bb4d25f8469471478195160fd96b5db7/BasicSample/app/src/androidTest/java/com/example/android/persistence/LiveDataTestUtil.java#L34

Why do you go the way with `CountDownLatch`  and not with `IdlingResource` ?

**Comment by ianhanniballake** [comment]
`LiveData` doesn't run on an executor that `IdlingResource` is aware of. A `CountDownLatch` allows the code to wait exactly until the observer is called.
