### ISSUE TITLE
After closing the application I am getting "Channel is unrecoverably broken and will be disposed!"

### ISSUE THREAD

**Issue by EugeneHoran** [android/architecture-components-samples#247]
After running the application I was look at the Logcat and noticed in the output:

12-09 17:22:03.433 1639-1720/system_process E/InputDispatcher: channel '8671a02 com.example.android.persistence/com.example.android.persistence.ui.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!

Any idea why this is happening?

**Comment by ianhanniballake** [comment]
This doesn't look related to the sample code provided here, nor Architecture Components in general. You can file a bug against the Android framework on [the issue tracker](https://issuetracker.google.com/issues/new?component=192705).
