### ISSUE TITLE
How to wait for postValue() in UI test

### ISSUE THREAD

**Issue by nuxzero** [android/architecture-components-samples#250]
I try to follow sample code but look like it not working to me. Can somebody help me check my code what I am wrong?

```kotlin 
@RunWith(AndroidJUnit4::class)
class AFragmentTest {

    @Rule
    @JvmField
    val activityRule = ActivityTestRule(MainActivity::class.java, true, true)

    private lateinit var fragment: AFragment
    private val viewModel = mock(AViewModel::class.java)
    private val listener = mock(AFragment.OnInteractionListener::class.java)
    private val liveData = MutableLiveData<Resource<A>>()

    @Before
    fun setUp() {
        fragment = AFragment()
        fragment.viewModel = viewModel
        `when`(viewModel.liveData).thenReturn(liveData)
        fragment.listener = listener
        activityRule.activity.replaceFragment(fragment)
    }

    @Test
    fun aTestSomeThing() {
        val a = A()
        liveData.postValue(Resource.success(a))
        verify(listener)?.onSuccess(a)
    }
}
```

If add `sleep` to wait for `postValue()` it working. But I think we should not do like this.

```kotlin
liveData.postValue(Resource.success(a))
sleep(1000)
```

**Comment by levibostian** [comment]
Here is a solution that is working for me (so far!) after browsing the source for this test suite. 

1. Make sure the Architecture Components test dependency is installed: `androidTestImplementation "androidx.arch.core:core-testing:2.0.0"`
2. In your test class, add the following test rule: `@get:Rule val countingTaskExecutorRule = CountingTaskExecutorRule()`
3. Anytime that you call `liveData.postValue()`, call: `countingTaskExecutorRule.drainTasks(3, TimeUnit.SECONDS)` (adjust the timeout to your liking) to wait for the tasks to all complete. 

Your test class above would look like this:

```kotlin
@RunWith(AndroidJUnit4::class)
class AFragmentTest {

    @Rule
    @JvmField
    val activityRule = ActivityTestRule(MainActivity::class.java, true, true)

    @Rule
    @JvmField 
    val countingTaskExecutorRule = CountingTaskExecutorRule()

    private lateinit var fragment: AFragment
    private val viewModel = mock(AViewModel::class.java)
    private val listener = mock(AFragment.OnInteractionListener::class.java)
    private val liveData = MutableLiveData<Resource<A>>()

    @Before
    fun setUp() {
        fragment = AFragment()
        fragment.viewModel = viewModel
        `when`(viewModel.liveData).thenReturn(liveData)
        fragment.listener = listener
        activityRule.activity.replaceFragment(fragment)
    }

    @Test
    fun aTestSomeThing() {
        val a = A()
        liveData.postValue(Resource.success(a))
        countingTaskExecutorRule.drainTasks(3, TimeUnit.SECONDS)
        verify(listener)?.onSuccess(a)
    }
}
```

I found this solution from browsing this repo and found [this test](https://github.com/googlesamples/android-architecture-components/blob/7bdc8d57f6829e473f42a62a7d18b088d92a0118/BasicSample/app/src/androidTest/java/com/example/android/persistence/ui/MainActivityTest.java).

**Comment by ianhanniballake** [comment]
`CountingTaskExecutorRule` is the correct class to use, yep.
