### ISSUE TITLE
Getting proguard error while using Room

### ISSUE THREAD

**Issue by ashwini009** [android/architecture-components-samples#251]
Warning:Supported source version 'RELEASE_7' from annotation processor 'android.arch.persistence.room.RoomProcessor' less than -source '1.8'
Warning:library class io.reactivex.internal.observers.ToNotificationObserver extends or implements program class io.reactivex.Observer
Warning:library class io.reactivex.internal.observers.ToNotificationObserver extends or implements program class io.reactivex.disposables.Disposable
Warning:library class io.reactivex.internal.operators.flowable.FlowableTimer$IntervalOnceSubscriber extends or implements program class org.reactivestreams.Subscription
Warning:library class io.reactivex.internal.operators.observable.ObservableRedo extends or implements program class io.reactivex.internal.operators.observable.AbstractObservableWithUpstream
Warning:library class io.reactivex.internal.operators.observable.ObservableRedo$1 extends or implements program class io.reactivex.functions.Consumer
Warning:library class io.reactivex.internal.operators.observable.ObservableRedo$RedoObserver extends or implements program class io.reactivex.Observer
Warning:library class io.reactivex.internal.operators.observable.ObservableTimer$IntervalOnceObserver extends or implements program class io.reactivex.disposables.Disposable
Warning:library class io.reactivex.internal.operators.single.SingleMap$1 extends or implements program class io.reactivex.SingleObserver
Warning:there were 8 instances of library classes depending on program classes.
Warning:Exception while processing task java.io.IOException: Please correct the above warnings first.
Error:Execution failed for task ':app:transformClassesAndResourcesWithProguardForProdRelease'.
> Job failed, see logs for details

@yigit Please help

**Comment by ianhanniballake** [comment]
This doesn't seem to be an issue with the samples. You can file an issue against Room on [the issue tracker](https://issuetracker.google.com/issues/new?component=413107) if you're still having an issue.
