### ISSUE TITLE
Issue with injected ViewModels (GithubBrowserSample)

### ISSUE THREAD

**Issue by yperess** [android/architecture-components-samples#257]
Hello, it's entirely possible that I've misused either Dagger or ViewHolderProvider.Factory but I believe I've found an issue in the GithubBrowserSample. I've created a project to demonstrate it: https://github.com/yperess/android-architecture-components and a corresponding StackOverflow question https://stackoverflow.com/questions/47874391/dagger-2-inject-viewmodel-odd-behavior-viewmodel-not-re-used-on-screen-rotation

Basically I have two concerns:
1. Injection is done in `onFragmentCreated` which is called after `Fragment::onCreate`, this means that the first time view models can be used is in `Fragment::onCreateView` as per the fragment lifecycle. This could cause duplicate observers if the fragment's view is destroyed and then recreated (coming back from the backstack). This is easily fixed by changing the injection point in AppInjector to `onFragmentPreCreated` and the logic of getting the view model and setting the observers into `Fragment::onCreate`.
2. If I try to inject the view model directly I get a new view model for every activity (even on screen rotations). To demonstrate this I've added an Activity and Fragment scope as well as a provider for a new MainViewModel that is shared between the SearchFragment and MainActivity. Indeed they both get the same instance of the MainViewModel, but the ViewModelProviders chooses to create a new view model even when the screen is rotated (my understanding is that it should return the same instance as before).

If this is due to my own misunderstanding of either Dagger or the architecture components I apologize for the erroneous issue.

**Comment by yperess** [comment]
To replicate the first simply search for a repo, open it, and hit back. You'll see that the live data from `getResult()` already has observers.

**Comment by JaehoJu** [comment]
https://developer.android.com/reference/android/support/v4/app/FragmentManager.FragmentLifecycleCallbacks.html#onfragmentprecreated
> This is a good time to inject any required dependencies or perform other configuration for the fragment.

**Comment by ianhanniballake** [comment]
You should always use `ViewModel.Factory`.
