### ISSUE TITLE
Nested ConstraintLayout using the <include> tag - "GithubBrowserSample"

### ISSUE THREAD

**Issue by androidmac** [android/architecture-components-samples#262]
Hi,

I've noticed that some of the layouts are using constraints and some don't..
So, looking at your example, I was wondering why you didn't build "loading_state.xml" with constraints? Is it because it is being included into another layout that is already using constraints?

Personally I've had some issues with including a ContraintLayout within another ConstraintLayout and that's why i'm asking!

Appreciate any answer and thank you for your time!

**Comment by BILLyTheLiTTle** [comment]
I don't think the "Issues" section is for this kind of "issues'!
But, you probably need this (https://stackoverflow.com/questions/43676415/how-to-include-constraint-layout-to-another-constraint-layout-and-set-constraint).

**Comment by ianhanniballake** [comment]
There's no reason to use `ConstraintLayout` when a simple `LinearLayout` with no nested layouts will do.
