### ISSUE TITLE
RxJava2 sample for PagingLibraryWithNetwork

### ISSUE THREAD

**Issue by vasimihalca** [android/architecture-components-samples#268]
On the current app, everything is rxjava2, no live data, I though to manage the lifecycle my own an decide when is the right moment to subscribe/unsubscribe in the view. 
I could not find any sample on how to use the new paging library with network + db using rxjava 2.
Only the live data seems available. 
I assume its a stupid question to ask: "can it be done with rxjava 2"?
I tried to implement a network paging mechanism using switchOnNext, but I'm not so happy with what i've got so far. 
Thanks!

**Comment by daimonkor** [comment]
Please provide sample Paging RxJava2, there are problems with hot or cold observables and reseting recyclerview after rotate device. Thanks for you support

**Comment by dlam** [comment]
In general, you can use something like https://github.com/uber/AutoDispose to manage lifecycle of your rx subscriptions.

We've also released an rx module along with Paging3's release that includes an operator for handling multicast + caching transformations and the Paging3 samples on d.android.com/paging now have explicit tabs for rxjava samples!
