### ISSUE TITLE
PersistenceMigrationsSample: Closing the database

### ISSUE THREAD

**Issue by johnjohndoe** [android/architecture-components-samples#275]
I noticed that the database connection is not explicitly closed in the _Room_ examples you provide in the _PersistenceMigrationsSample_ project. I would have expected `database.close()` at some point. The database is initialized in [`LocalUserDataSource`](https://github.com/googlesamples/android-architecture-components/blob/master/PersistenceMigrationsSample/app/src/room_common/java/com/example/android/persistence/migrations/LocalUserDataSource.java#L41). Can you please explain why it is not needed if so?

Contrary, in the unit test [the in-memory database is torn down](https://github.com/googlesamples/android-architecture-components/blob/master/PersistenceMigrationsSample/app/src/androidTestRoom/java/com/example/android/persistence/migrations/UserDaoTest.java#L50) via `database.close()` in `@After`.

**Comment by ianhanniballake** [comment]
All resources are freed up when the application process is destroyed (which would be when a singleton like `LocalUserDataSource` is destroyed).
