### ISSUE TITLE
AndroidTest fails with DexArchiveMergerException: Unable to merge dex

### ISSUE THREAD

**Issue by johnjohndoe** [android/architecture-components-samples#282]
The following error is output when I run the `androidTestRoom3.LocalUserDataSourceTest` in the `PersistenceMigrationsSample` project:

> Error:Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForRoom3Debug'.
> java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex

# Environment
- Android Studio: 3.0.1
- Connected device: Nexus 5, Android 6.0.1
- Commit checked out: 0b72faa72efe9c9758e8e99ac8ccca839a25cdfb

# Related issue
- #5

**Comment by modislaszlox2** [comment]
I' having the same issue with custom test, any workaround for it?

```
Execution failed for task ':cloud-service:transformDexArchiveWithExternalLibsDexMergerForDebugAndroidTest'.
> java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex
```

**Comment by ianhanniballake** [comment]
Seems to be working fine now.

**Comment by johnjohndoe** [comment]
@ianhanniballake, actually: No. See #801. How did you test the execution of the Android Test?

**Comment by ianhanniballake** [comment]
Yep, good catch. I was running the wrong test of tests
