### ISSUE TITLE
GitHubBrowserSample: Exposing SingleLiveEvent for Retrofit

### ISSUE THREAD

**Issue by AkshayChordiya** [android/architecture-components-samples#298]
The GitHubBrowerSample uses `LiveData` for Room and Retrofit while it doesn't make sense to have `LiveData` for Retrofit as it's a one-off event.
Exposing [`SingleLiveEvent`](https://github.com/googlesamples/android-architecture/blob/dev-todo-mvvm-live/todoapp/app/src/main/java/com/example/android/architecture/blueprints/todoapp/SingleLiveEvent.java) makes more sense instead of `LiveData`

**Comment by shakil807g** [comment]
@AkshayChordiya but with SingleLiveEvent  will not trigger the cache data when config change occur

**Comment by ianhanniballake** [comment]
Yep, you want `LiveData` for immediately returning cached values.
