### ISSUE TITLE
Error:Could not resolve all files for configuration ':app:debugCompileClasspath'.

### ISSUE THREAD

**Issue by zhoujingheng** [android/architecture-components-samples#302]
Error:Could not resolve all files for configuration ':app:debugCompileClasspath'.
> Could not resolve android.arch.persistence.room:runtime:1.1.0-alpha1.
  Required by:
      project :app
   > Could not resolve android.arch.persistence.room:runtime:1.1.0-alpha1.
      > Could not get resource 'https://dl.google.com/dl/android/maven2/android/arch/persistence/room/runtime/1.1.0-alpha1/runtime-1.1.0-alpha1.pom'.
         > Could not GET 'https://dl.google.com/dl/android/maven2/android/arch/persistence/room/runtime/1.1.0-alpha1/runtime-1.1.0-alpha1.pom'.
            > dl.google.com
> Could not resolve android.arch.lifecycle:runtime:1.1.0.
  Required by:
      project :app
   > Could not resolve android.arch.lifecycle:runtime:1.1.0.
      > Could not get resource 'https://dl.google.com/dl/android/maven2/android/arch/lifecycle/runtime/1.1.0/runtime-1.1.0.pom'.
         > Could not GET 'https://dl.google.com/dl/android/maven2/android/arch/lifecycle/runtime/1.1.0/runtime-1.1.0.pom'.
            > 杩欐槸鍦ㄤ富鏈哄悕瑙ｆ瀽鏃堕?氬父鍑虹幇鐨勬殏鏃堕敊璇紝瀹冩剰鍛崇潃鏈湴鏈嶅姟鍣ㄦ病鏈変粠鏉冨▉鏈嶅姟鍣ㄤ笂鏀跺埌鍝嶅簲銆? (dl.google.com)
> Could not resolve android.arch.lifecycle:extensions:1.1.0.
  Required by:
      project :app
   > Could not resolve android.arch.lifecycle:extensions:1.1.0.
      > Could not get resource 'https://dl.google.com/dl/android/maven2/android/arch/lifecycle/extensions/1.1.0/extensions-1.1.0.pom'.
         > Could not GET 'https://dl.google.com/dl/android/maven2/android/arch/lifecycle/extensions/1.1.0/extensions-1.1.0.pom'.
            > dl.google.com
> Could not resolve android.arch.lifecycle:common-java8:1.1.0.
  Required by:
      project :app
   > Could not resolve android.arch.lifecycle:common-java8:1.1.0.
      > Could not get resource 'https://dl.google.com/dl/android/maven2/android/arch/lifecycle/common-java8/1.1.0/common-java8-1.1.0.pom'.
         > Could not GET 'https://dl.google.com/dl/android/maven2/android/arch/lifecycle/common-java8/1.1.0/common-java8-1.1.0.pom'.
            > dl.google.com
> Could not resolve android.arch.lifecycle:runtime:1.1.0.
  Required by:
      project :app > com.android.support:recyclerview-v7:26.1.0 > com.android.support:support-compat:26.1.0
   > Could not resolve android.arch.lifecycle:runtime:1.1.0.
      > Could not get resource 'https://dl.google.com/dl/android/maven2/android/arch/lifecycle/runtime/1.1.0/runtime-1.1.0.pom'.
         > Could not GET 'https://dl.google.com/dl/android/maven2/android/arch/lifecycle/runtime/1.1.0/runtime-1.1.0.pom'.
            > 杩欐槸鍦ㄤ富鏈哄悕瑙ｆ瀽鏃堕?氬父鍑虹幇鐨勬殏鏃堕敊璇紝瀹冩剰鍛崇潃鏈湴鏈嶅姟鍣ㄦ病鏈変粠鏉冨▉鏈嶅姟鍣ㄤ笂鏀跺埌鍝嶅簲銆? (dl.google.com)

**Comment by cnqiuxue** [comment]
me too

**Comment by ianhanniballake** [comment]
This doesn't seem be an issue with the samples. You can file an issue on [the issue tracker](https://issuetracker.google.com/issues/new?component=197448) if you're still having an issue.
