### ISSUE TITLE
Markdown syntax mistakes in CONTRIBUTING.md

### ISSUE THREAD

**Issue by matkoniecz** [android/architecture-components-samples#325]
https://github.com/googlesamples/android-architecture-components/blob/master/CONTRIBUTING.md has incorrect syntax for links, for example

> you'll need to sign an [individual CLA] (https://cla.developers.google.com).

I would make a PR, but I see a [queue of old unhandled ones](https://github.com/googlesamples/android-architecture-components/pulls).

**Comment by florina-muntenescu** [comment]
Feel free to do a PR for the CONTRIBUTING.md file.
