### ISSUE TITLE
clearing sqlite_sequence is not working in android room

### ISSUE THREAD

**Issue by uday-ks** [android/architecture-components-samples#330]
Following code is not resetting/clearing the auto increment id to 0

`database = Room.databaseBuilder(getApplicationContext(), AppDatabase.class,DatabaseMeta.DB_NAME).build();`

`database.query("DELETE FROM sqlite_sequence WHERE name = ?", new Object[]{"tableName"});`

Is there any other way to clear "sqlite_sequence"?

Android room is not using "sqlite_sequence" for auto increment i think, not sure.

**Comment by lvabarajithan** [comment]
I'm sure room is using "sqlite_sequence".. But I too face this problem

**Comment by wavehunterhawk** [comment]
Im also faced with the same problem!  not sure how I can reset auto increment id to 0

**Comment by HasanElHefnawy** [comment]
As per the answers given [here](https://www.askingbox.com/question/sqlite-reset-autoincrement), and [here](https://stackoverflow.com/a/50883758/9863904), and [here](https://stackoverflow.com/a/53764393/9863904), I could do it as following:
`public void deleteAndReset() {`
`        SQLiteDatabase database;`
`        database = SQLiteDatabase.openOrCreateDatabase(getDatabasePath(MY_DATABASE_NAME), null);`
`        String deleteTable = "DELETE FROM " + MY_TABLE_NAME;`
`        database.execSQL(deleteTable);`
`        String deleteSqliteSequence = "DELETE FROM sqlite_sequence WHERE name = '" + MY_TABLE_NAME + "'";`
`        database.execSQL(deleteSqliteSequence);`
`}`

**Comment by ianhanniballake** [comment]
This doesn't seem to be an issue with the samples. You can file an issue against Room on [the issue tracker](https://issuetracker.google.com/issues/new?component=413107) if you're still having an issue / have a feature request.
