### ISSUE TITLE
README.md - Lifecycle-Aware Components

### ISSUE THREAD

**Issue by taurelas** [android/architecture-components-samples#332]
It says

"A collection of samples using(...) Lifecycle-aware components (...)"

but then no sample is described as using them.

This is of no help to someone who is looking for how to create a Lifecycle-aware component. 

This repo is linked to by "Lifecycle-aware components" [guide](https://developer.android.com/topic/libraries/architecture/lifecycle.html)

**Comment by ianhanniballake** [comment]
Every sample uses `Lifecycle` or existing `LifecycleOwner` implementations in your activity and fragment instances along with APIs like `LiveData` that take advantage of `Lifecycle`. Generally, the focus of samples is on the common use cases and building your own `LifecycleOwner` is not a common use case.
