### ISSUE TITLE
Using database.query() in a Room migration causes IllegalStateException

### ISSUE THREAD

**Issue by DCRichards** [android/architecture-components-samples#334]
My migration is complex and requires migrating from a table with a single column of serialised data to a proper schema with distinct columns. I know, I know... it didn't matter at the time. 

Most importantly, this means migration requires manually deserialising the data and then re-inserting it in the new table. The migration has the following:

```kotlin
private val migration = object: Migration(1, 2) {
    override fun migrate(database: SupportSQLiteDatabase) {
         val dc = database.query("SELECT * FROM $DASH_TILES_TABLE")
         // at this point we should be parsing the cursor and deserialising, but instead this throws an error
     }
}
```

This is then throws the following:
`java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase: /data/user/0/io.oplift.engage.dev/databases/opliftengage.db`. So, are migrations not allowed to query data? Or is this a bug? Has anyone else come across this?

**Comment by ianhanniballake** [comment]
This doesn't seem to be an issue with the samples. You can file an issue against Room on [the issue tracker](https://issuetracker.google.com/issues/new?component=413107) if you're still having an issue.
