### ISSUE TITLE
Android Studio new project will auto dependencies ?

### ISSUE THREAD

**Issue by werbhelius** [android/architecture-components-samples#336]
<img width="411" alt="20180409162906" src="https://user-images.githubusercontent.com/12763277/38487631-723d038c-3c13-11e8-9f12-a02cd49239f0.png">

Like this pic , i just create a new project, and it will auto dependencies version 1.1.0

how can i remove this or change version to 1.1.1 ?

when i dependencies version 1.1.1 in my gradle file , it will get this error

<img width="749" alt="20180409163409" src="https://user-images.githubusercontent.com/12763277/38487780-e40ddafe-3c13-11e8-8a69-efc9d15eb8e8.png">

**Comment by Werb** [comment]
support v7 will auto dependencies version 1.1.0?

**Comment by Guaidaodl** [comment]
From the error message. you should set the version lifecycle compiler as 1.1.1.

**Comment by ianhanniballake** [comment]
This doesn't seem to be an issue with the samples. You can file an issue against Lifecycle on [the issue tracker](https://issuetracker.google.com/issues/new?component=413132) if you're still having an issue.
