### ISSUE TITLE
How to Export and Import the database/data using Android Room Library?

### ISSUE THREAD

**Issue by hasnain-ahmad** [android/architecture-components-samples#340]
I have developed two android application using the _[ActiveAndroid](https://github.com/pardom-zz/ActiveAndroid)_ library. Currently, I am posting all database tables' data to Server (MS SQL Server) for some reasons some data is not synced to the server. I want to backup the database file to sd card and also on the google drive and ask the user to share the database via email from sd card/google drive. So that I can see unsynced data and track the issue and sync/insert the data manually via queries in the server database. 

I have googled a lot and found that many android database libraries have no built-in functionality for exporting and importing the SQLite database. 

Is Android Room library has the functionality of export and imports the database? If not please add this functionality in the library it will be helpful for developers to handle database and related issues also for clients to share the database easily.

**Comment by hasnain-ahmad** [comment]
@MONIKA-KUMAR-JETHANI Yes the above mentioned issue/functionality is still pending!

**Comment by ValmirJuniorr** [comment]
I've the same problem, and i would like to find a way to do that.

**Comment by lumakhl** [comment]
The function was implemented? Somebody know anything about this?

**Comment by prabinshrestha** [comment]
Anybody knows the answer please?

**Comment by or-dvir** [comment]
### warning
i have literally just figured this out and have not yet fully tested this but for now it seems to work.
so far i have only tested that a file with some content is being created in local storage, sd card, and google drive.

### solution
1) let user choose location using ACTION_CREATE_DOCUMENT **(required API 19)**
2) get db file using getDatabasePath(DATABASE_NAME)
3) use contentResolver wiht input/output streams to copy contents.

this code sample is shortened for brevity.
this sample is in kotlin, but the java version should be similar

```
//somewhere in the code:
val intent = Intent(Intent.ACTION_CREATE_DOCUMENT)
intnet.type = "*/* // this line is a must when using ACTION_CREATE_DOCUMENT
startActivityForResult(intent, REQUEST_CODE)


override fun onActivityResult(...)
{
    //null and exception handling omitted for brevity

    val userChosenUri = data.data
    val inStream = getDatabasePath(DATABASE_NAME).inputStream()
    val outStream = contentResolver.openOutputStream(userChosenUri)
  
    inStream.use { input ->
        outStream.use { output ->
                            input.copyTo(output)
        }
     }
}
```

**Comment by KathiriyaHP** [comment]
If Any have soluation about how to export roomdb to sdcard then give sample code

**Comment by or-dvir** [comment]
@KathiriyaHP does my solution not work for sd card?

**Comment by jiulian** [comment]
> If Any have soluation about how to export roomdb to sdcard then give sample code

### Note: You also need to copy the "-shm" and "-wal" files
(Reason: https://stackoverflow.com/questions/50372487/android-room-database-file-is-empty)

It works for me:


fun exportDatabaseFile(context: Context) {
        try {
            val sd = File(Environment.getExternalStorageDirectory().path + "/Download/")

            if (sd.canWrite()) {
                val currentDBPath = context.getDatabasePath(Constant.DATABASE_NAME_WITH_FORMAT).absolutePath
                val currentDB_shm_Path = context.getDatabasePath(Constant.DATABASE_NAME_WITH_FORMAT).absolutePath + "-shm"
                val currentDB_wal_Path = context.getDatabasePath(Constant.DATABASE_NAME_WITH_FORMAT).absolutePath + "-wal"
                val backupDBPath = "backup_" + Constant.DATABASE_NAME_WITH_FORMAT
                val backupDB_shm_Path = "backup_" + Constant.DATABASE_NAME_WITH_FORMAT + "-shm"
                val backupDB_wal_Path = "backup_" + Constant.DATABASE_NAME_WITH_FORMAT + "-wal"

                writeDataFromOneToAnother(currentDBPath, backupDBPath, sd)
                writeDataFromOneToAnother(currentDB_shm_Path, backupDB_shm_Path, sd)
                writeDataFromOneToAnother(currentDB_wal_Path, backupDB_wal_Path, sd)
            }
        } catch (e: Exception) {
            e.printStackTrace()
        }
    }

private fun writeDataFromOneToAnother(firstPath: String, secondPath: String, destinationFile: File) {
        val firstFile = File(firstPath)
        val secondFile = File(destinationFile, secondPath)
        if (firstFile.exists()) {
            val src = FileInputStream(firstFile).channel
            val dst = FileOutputStream(secondFile).channel
            dst.transferFrom(src, 0, src.size())
            src.close()
            dst.close()
        }
    }


Modified codes from: 
https://stackoverflow.com/questions/44986465/where-room-save-database-android

**Comment by pravbeseda** [comment]
This is a non-working solution. Root rights are required to copy the database created by Room.databaseBuilder. On the line `val inStream = getDatabasePath("base.db"). InputStream()`, we get **FileNotFoundException**. getDatabasePath returns the correct path, the file is there, but the application does not see it. Or am I doing something wrong. Checked on emulators and a real smartphone. android.arch.persistence.room:runtime:1.1.1

**Comment by pravbeseda** [comment]
Sorry my mistake. The database is not available for download, if you create it by the standard path, such as /data/user/0/com.app/databases/base.db. But if when creating a database, specify the path such as /storage/emulated/0/folder/wallets.db - your solution is work! Thanks.

**Comment by pravbeseda** [comment]
> do we have to specify the path when building room database with "Room.databaseBuilder?"

Yes.

`Room.databaseBuilder<AppDatabase>(context,  AppDatabase::class.java, databasePath)`

**Comment by ianhanniballake** [comment]
This doesn't seem to be an issue with the samples. You can file an issue against Room on [the issue tracker](https://issuetracker.google.com/issues/new?component=413107) if you're still having an issue.

**Comment by hasnain-ahmad** [comment]
> This doesn't seem to be an issue with the samples. You can file an issue against Room on [the issue tracker](https://issuetracker.google.com/issues/new?component=413107) if you're still having an issue.

I have posted at the following link.
https://issuetracker.google.com/issues/154588984

**Comment by KathiriyaHP** [comment]
Solved the issue
