### ISSUE TITLE
Please suggest a NetworkBoundResource version with Paging library?

### ISSUE THREAD

**Issue by prdp89** [android/architecture-components-samples#348]
Hi,

Now PagingWithNetwork sample already demonstrates Paging inside DbRedditPostRepository. 

Can somebody suggest how to use this class to leverage NetworkBoundResource and Paging with Java?

We are already using Arch component in our App, just stuck with paging implementation.

Thanks,
Pardeep Sharma.

**Comment by rhexgomez** [comment]
IMO If you use `WorkManager` and `Room` you do not a `NetworkBoundResource`, just listen to your Room-database as if the network logic never exists at all and let the `WorkManager` do syncing.

**Comment by dlam** [comment]
While the post is quite old - layered datasource should be done via `BoundaryCallback` in Paging2 and `RemoteMediator` in Paging3.
