### ISSUE TITLE
The ViewHolder in BasicSample is sad :(

### ISSUE THREAD

**Issue by Zhuinden** [android/architecture-components-samples#353]
https://github.com/googlesamples/android-architecture-components/blob/99aeb346caef2c545c98df953dfdeb3b50bb013d/BasicSample/app/src/main/java/com/example/android/persistence/ui/ProductAdapter.java#L92-L93

``` java
    @Override
    public void onBindViewHolder(CommentViewHolder holder, int position) {
        holder.binding.setComment(mCommentList.get(position));
        holder.binding.executePendingBindings();
    }
```

I'd expect this to be

```java
    @Override
    public void onBindViewHolder(CommentViewHolder holder, int position) {
        holder.bind(mCommentList.get(position));
    }
```

to eliminate the "sad ViewHolder pattern".

**Comment by ianhanniballake** [comment]
This is a stylistic choice to ensure that developers know that they need to call `executePendingBindings()` in `onBindViewHolder()`.
