### ISSUE TITLE
create new table

### ISSUE THREAD

**Issue by YougaKing** [android/architecture-components-samples#358]
![image](https://user-images.githubusercontent.com/16010591/39863392-1c63e010-5479-11e8-9cf6-5f22c5016cef.png)
    TableInfo{name='Banner', columns={link_title=Column{name='link_title', type='TEXT', notNull=false, primaryKeyPosition=0}, can_close=Column{name='can_close', type='INTEGER', notNull=true, primaryKeyPosition=0}, show_type=Column{name='show_type', type='INTEGER', notNull=true, primaryKeyPosition=0}, id=Column{name='id', type='INTEGER', notNull=true, primaryKeyPosition=1}, image=Column{name='image', type='TEXT', notNull=false, primaryKeyPosition=0}, link_type=Column{name='link_type', type='INTEGER', notNull=true, primaryKeyPosition=0}, localType=Column{name='localType', type='TEXT', notNull=false, primaryKeyPosition=0}, use_type=Column{name='use_type', type='INTEGER', notNull=true, primaryKeyPosition=0}, update_time=Column{name='update_time', type='INTEGER', notNull=true, primaryKeyPosition=0}, create_time=Column{name='create_time', type='INTEGER', notNull=true, primaryKeyPosition=0}, link_content=Column{name='link_content', type='TEXT', notNull=false, primaryKeyPosition=0}}, foreignKeys=[], indices=[]}
     Found:
    TableInfo{name='Banner', columns={}, foreignKeys=[], indices=null}
create new table banner why？

**Comment by georgetsiga** [comment]
Hi @YougaKing 

I know you might have solved this but for others who might find themselselves in the same situation.
You must implement room datamigration correctly by writing the create table sql statement. eg


`Room.databaseBuilder(getApplicationContext(), MyDb.class, "database-name")
        .addMigrations(MIGRATION_1_2, MIGRATION_2_3).build();

static final Migration MIGRATION_1_2 = new Migration(1, 2) {
    @Override
    public void migrate(SupportSQLiteDatabase database) {
        database.execSQL("CREATE TABLE `'Banner` (`id` INTEGER, "
                + "`link_title` TEXT, PRIMARY KEY(`id`))");
    }
};`

Please go through the whole tutorial [here](https://developer.android.com/training/data-storage/room/migrating-db-versions).

Happy coding.

**Comment by JiongBull** [comment]
![image](https://user-images.githubusercontent.com/4413502/44447645-63977c00-a61b-11e8-9971-280b6a8e3d71.png)

@georgetsiga hi, do you know why 'origin' is -1.

**Comment by georgetsiga** [comment]
HI @JiongBull   -1 means the column name does not exist.

Please check out the Android documentation on Cursors.

**Comment by JiongBull** [comment]
@georgetsiga thanks for your reply, i found my Migration always failed, although i have created index, so i debug it to find the reason, at last i found that my index doesn't have the field 'origin'.

``` java
database.execSQL("CREATE UNIQUE INDEX index_cabinet_cabinet_index ON cabinet (cabinet_index)");
```

java.lang.IllegalStateException: Migration failed. expected:TableInfo{name='cabinet', columns={cabinet_index=Column{name='cabinet_index', type='INTEGER', affinity='3', notNull=true, primaryKeyPosition=0}, alias=Column{name='alias', type='TEXT', affinity='2', notNull=false, primaryKeyPosition=0}, code=Column{name='code', type='TEXT', affinity='2', notNull=true, primaryKeyPosition=1}}, foreignKeys=[], indices=[Index{name='index_cabinet_cabinet_index', unique=true, columns=[cabinet_index]}]} , found:TableInfo{name='cabinet', columns={cabinet_index=Column{name='cabinet_index', type='INTEGER', affinity='3', notNull=true, primaryKeyPosition=0}, alias=Column{name='alias', type='TEXT', affinity='2', notNull=true, primaryKeyPosition=0}, code=Column{name='code', type='TEXT', affinity='2', notNull=true, primaryKeyPosition=1}}, foreignKeys=[], indices=null}

**Comment by ianhanniballake** [comment]
This doesn't seem to be an issue with the samples. You can file an issue against Room on [the issue tracker](https://issuetracker.google.com/issues/new?component=413107) if you're still having an issue.
