### ISSUE TITLE
Room does not work with data binding

### ISSUE THREAD

**Issue by dp-2910** [android/architecture-components-samples#361]
I have create one project that uses a data binding library, but whenever i use room library in my project i have found an error like follow. 

```
error: package com.example.project.databinding does not exist
import com.example.project.databinding.ActivityTutorialScreenBinding;
                                      ^

error: cannot find symbol
private ActivityTutorialScreenBinding binding;
        ^
symbol:   class ActivityTutorialScreenBinding
location: class IntroducationScreen
```
Please help me out if any one found solution of this issue.
Thanks

**Comment by EduardoDornel** [comment]
i have same error

**Comment by YuganshT79** [comment]
Having the same issue with Room and DataBinding 😢

**Comment by chezi** [comment]
Hi, i solved the issue by creating  a new module for room

**Comment by angopa** [comment]
@chezi Can you tell me more about your implementation? I did the same, move my room to a new module, and I could compile the project, but when I try to create my instance AppDatabase.INSTANCE(), it say `Cannot access androdx.room.RoomDatabase`.

**Comment by angopa** [comment]
Hi, I solve this problem just fixing SQL query. The problem as that **userId** was incorrect,
`@Query("SELECT * FROM User WHERE userId = :userId")` the name of the row in the table was `user_id`. Just fixing that and everything works fine.

**Comment by suvojitd79** [comment]
I had the same issue. After spending hours on this, I finally fixed the error by replacing `LiveData<ArrayList<MovieFavEntity>>` to `LiveData<List<MovieFavEntity>>` . Just check the return type and queries of the different method in the Dao.

**Comment by amrro** [comment]
I guess this problem is related to `kapt` or `annotationProcessor` itself not room. 
When the build fails, the databinding fails to generate these files too and Android Studio throws all errors to your face. 

So you might need to go to the first error in the log or temporarily  change `kapt` to `annotationProcessor` and rebuild to get clear error.

**Comment by urvish91** [comment]
Hello Team, I am facing the same issue which is raised. Can you please quickly look into that and fix this bug as soon as possible. as it impacts a lot for large scale project.

**Comment by SikanderBakht** [comment]
After enabling data binding
"dataBinding {
        enabled = true
    }"
I get
"[kapt] An exception occurred: java.lang.ExceptionInInitializerError"

**Comment by urvish91** [comment]
It is working fine. you just need to use the latest versions of kotlin and room. I was also facing the issues earlier when I was also using dagger but after that when I switched to KOIN and used all latest versions it is working fine.

**Comment by ianhanniballake** [comment]
This doesn't seem to be an issue with the samples. You can file an issue against Room on [the issue tracker](https://issuetracker.google.com/issues/new?component=413107) if you're still having an issue.
