### ISSUE TITLE
Add option to change Fragment transition z-order in Navigation Arch Component

### ISSUE THREAD

**Issue by eerikk** [android/architecture-components-samples#365]
Just tried out new Navigation Architecture Component and it looks promising.

One thing that has been a problem with Fragment transactions is the z-order of fragment transition animations.

Example- When you want new fragment to slide on top of the old one, then currently the only solution is using .add() which may create memory issues. Now that we're moving from Fragment transactions to Navigation component, then I expect it to solve this problem as well.

What I'm expecting from Navigation Arch Component- easily set z-order of enter/exit transitions, in a way that you wouldn't need to worry about memory issues or anything else.

**Comment by Zhuinden** [comment]
Wouldn't that mean it only works on API 21+?

**Comment by kakai248** [comment]
I created an issue for this: https://issuetracker.google.com/issues/79443865

**Comment by ianhanniballake** [comment]
See the updated progress on the issue tracker linked above.

**Comment by Zhuinden** [comment]
There's a good chance that using FragmentContainerView solves this
