### ISSUE TITLE
can't import NavigationBasicSample and GithubBrowserSample

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [android/architecture-components-samples#366]
For NavigationBasicSample, I get this:

![image](https://user-images.githubusercontent.com/5357526/40343790-5c2f9912-5d9a-11e8-9333-79841456ab08.png)

And for GithubBrowserSample I get this:

![image](https://user-images.githubusercontent.com/5357526/40344043-9ad44b8a-5d9b-11e8-8e8a-ef1a37a1baf1.png)

**Comment by shanuka** [comment]
update your  gradle-wrapper.properties with this 
distributionUrl=https\://services.gradle.org/distributions/gradle-4.7-all.zip

**Comment by AndroidDeveloperLB** [comment]
@shanuka It already suggested me to update. It didn't help.
See attached videos.
[1.zip](https://github.com/googlesamples/android-architecture-components/files/2025124/1.zip)

**Comment by shanuka** [comment]
update your version gradle file manually

**Comment by AndroidDeveloperLB** [comment]
This solved it, but why? Why can't the sample work from start?

This is what I did. Instead of this:

    classpath deps.android_gradle_plugin

I've put this:

    classpath 'com.android.tools.build:gradle:3.2.0-alpha15'

**Comment by AndroidDeveloperLB** [comment]
Why downvote?
Also, please fix the sample

**Comment by AndroidDeveloperLB** [comment]
BTW, I already use 3.2:
Android Studio 3.2 Canary 15
Build #AI-181.4668.68.32.4773949, built on May 10, 2018
JRE: 1.8.0_152-release-1136-b03 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by shanuka** [comment]
update in your version.gradle file
versions.android_gradle_plugin = "3.2.0-alpha15"

**Comment by AndroidDeveloperLB** [comment]
@shanuka The IDE failed to do it on its own. Please fix either the IDE or the sample, then.

**Comment by ianhanniballake** [comment]
Seems fine now.

**Comment by AndroidDeveloperLB** [comment]
@ianhanniballake I tried now. Seems to work well. Thanks.
