### ISSUE TITLE
Build Failed for GithubBrowserSample 

### ISSUE THREAD

**Issue by firatkarababa** [android/architecture-components-samples#368]
When I try to run GithubBrowserSample I get the following build error. I am using Android Studio 3.2 and android_gradle_plugin = "3.2.0-alpha15"

w: C:\Users\firat-pc\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-stdlib-jre7\1.2.41\9e7a6f582de73d9cdc6c56ef4e23604a0ee55768\kotlin-stdlib-jre7-1.2.41.jar: kotlin-stdlib-jre7 is deprecated. Please use kotlin-stdlib-jdk7 instead

**Comment by shanuka** [comment]
actullay this warning 
find in version.gradle 
~~~
kotlin.stdlib = "org.jetbrains.kotlin:kotlin-stdlib-jre7:$versions.kotlin"
~~~
replace with
~~~
kotlin.stdlib = "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$versions.kotlin"
~~~

**Comment by Zhuinden** [comment]
Probably outdated tooling for Navigation-related things

**Comment by firatkarababa** [comment]
@Zhuinden such as?

**Comment by ianhanniballake** [comment]
Seems to be working now.
