### ISSUE TITLE
Provide sample for DB only pagination

### ISSUE THREAD

**Issue by kagile** [android/architecture-components-samples#371]
How to paginate with the only db and offset in query with Room?

**Comment by ChrisCraik** [comment]
The Paging sample shows how to page with only the DB: https://github.com/googlesamples/android-architecture-components/tree/master/PagingSample

Do you mean for a query with the keyword OFFSET already in it?

**Comment by kagile** [comment]
@ChrisCraik 

> Do you mean for a query with the keyword OFFSET already in it?
- Yes

**Comment by kagile** [comment]
@ChrisCraik 
I have a chat application in which all messages are to be loaded from bottom to top.
First I want to show only 100 messages and then paginate them by 20. 
I used the paging library with room but it is giving all the data at once. 
There is no list insertion observability supported in live data afaik.
How do I paginate in that case?
Should I need to create custom data source by extending PositionalDataSource?
Or is there any suggestion or help you can provide for those scenarios?

**Comment by Zhuinden** [comment]
Considering you expect the data source to return a different number based on 

The built-in mechanism is to support scrolling 10000 items as if it were just 60 from the user perspective, as in you don't need to manually paginate.

Now if you do want to manually paginate, you'll need a custom positional data source that mimics `LimitOffsetDataSource` in Room, which receives a maximum item count as an input parameter from the DataSource.Factory.

So the DataSource.Factory is asked by LivePagedListBuilder to build a new list on invalidation, but DataSource.Factory is also asked to recreate the list when you scroll to bottom and want to load more.

So with pseudocode your loader would be something like

``` java
    public class PagedDataSourceFactory<T> extends DataSource.Factory<Integer, T> {
        private int initialMax;
        private int loadCount;

        private int loadedPageCount = 0;

        private PagedDataSource<T> dataSource;

        public PagedDataSourceFactory(int initialMax, int loadCount) {
             this.initialMax = initialMax;
             this.loadCount = loadCount; // f.ex. 100, 20
        }

       @Override
       public DataSource<T> create() {
            this.pagedDataSource = new PagedDataSource<>(initialMax + loadCount * loadedPageCount); // current max count
            return pagedDataSource;
       }

       public void loadMore() {
           loadedPageCount++;
           if(pagedDataSource != null) {
                pagedDataSource.invalidate();
           }
       }
```

or something like that.

**Comment by ChrisCraik** [comment]
Can you be more specific about what you tried and what you expect? It sounds like you are hitting three problems:

1. Paging returning too many items - I'm not aware of any cases where paging will load too many items, except for placeholders making it look like that's the case. A repro project would be helpful.

1. Listening to updates - If you want to listen to pages as they are inserted into the current PagedList, you can by subscribing/unsubscribing in onCurrentListUpdated() via calling pagedList.addWeakCallback(null, myCallback). Note that this will only tell you about new pages loaded after the PagedList is switched. It doesn't signal updates when the PagedLists are swapped.

1. OFFSET - We don't currently support the OFFSET keyword in those queries, you can file a bug to request it: https://issuetracker.google.com/issues/new?component=413106&template=1096385
Is may be possible to use something like "WHERE ID >= ..." to workaround this, but it would help if you could explain more of what you're trying to do.

A sample project would be helpful in helping me understand,
Thanks

**Comment by kagile** [comment]
@ChrisCraik https://issuetracker.google.com/issues/79845208

**Comment by ianhanniballake** [comment]
It looks like the issue mentioned above has been resolved. Feel free to file any additional issues against Paging on [the issue tracker](https://issuetracker.google.com/issues/new?component=413106).
