### ISSUE TITLE
Adding WorkManager dependency with Kotlin - Kotlin Compiler: unknown enum constant Scope.LIBRARY_GROUP

### ISSUE THREAD

**Issue by chrisrohitbrendan** [android/architecture-components-samples#374]
I'm trying to use WorkManager but I'm getting the following error with Kotlin: 

![problem](https://user-images.githubusercontent.com/29043991/40536572-4308caa2-602a-11e8-9bb6-ef644534999b.png)

I've tried adding the support library and arch dependencies, but it doesn't work.

**Comment by ianhanniballake** [comment]
This doesn't seem to be an issue with the samples.
