### ISSUE TITLE
databinding with navigation

### ISSUE THREAD

**Issue by wangyangzi** [android/architecture-components-samples#378]
##issue with navigation 

when i use databinding architecture together with navigation，it doesn't work this fun onBackPressed(), How can i  to deal with it?  anyone have some comments...

**Comment by paulkugaev** [comment]
override onBackPressed() to call onSupportNavigateUp()

in my project I check if i'm in first fragment in graph

`override fun onBackPressed() {
        val currentDestination = navController.currentDestination
        val parent = currentDestination.parent
        if (parent == null || currentDestination.id != parent.id)
            super.onBackPressed()
        else
            onSupportNavigateUp()
    }`

**Comment by mattmook** [comment]
You shouldn't need to look at the destinations, instead just try to move up in the `navController`.

```
if (!navController.popBackStack()) {
    super.onBackPressed()
}

```

Note: I've used `popBackStack()` as the documentation implies this is the more appropriate call for when the user presses the back button, but equally `navigateUp()` also tells you whether it did anything so can be used instead.

**Comment by AdamSHurwitz** [comment]
@wangyangzi I'm using **databinding** architecture together with **navigation components** and had many issues working with the **NavController**. 

I was only able to the the back button logic to work using `Navigation.createNavigateOnClickListener`. I passed the view from the layout to the **ViewModel**.

`android:onClick="@{(v) -> viewmodel.profileButtonClick(v)}"`

Then from the ViewModel I passed the view down to the **Fragment** using **LiveData**.

```
    var profileButtonClick = MutableLiveData<View>()

    fun profileButtonClick(view: View) {
        profileButtonClick.value = view
    }
```
Then you can use it in the view.

```
viewModel.profileButtonClick.observe(viewLifecycleOwner, Observer { view ->
                view.setOnClickListener(Navigation.createNavigateOnClickListener(
                        R.id.action_homeFragment_to_profileFragment, null))
```

**Comment by Raj-Varun** [comment]
I'm unable to go to the next fragment.

https://stackoverflow.com/questions/57176286/navigation-is-not-working-when-using-viewmodel

**Comment by ianhanniballake** [comment]
This doesn't seem like any issue with the sample. Please file issues against Navigation on [the issue tracker](https://issuetracker.google.com/issues/new?component=409828) if you're still running into issues.
