### ISSUE TITLE
Unable to set network result at NetworkBoundResource

### ISSUE THREAD

**Issue by saurabhmdh** [android/architecture-components-samples#381]
Hello,

I am trying to adopt this design under my project but there is small change in my requirement at present I don't want to use database to store network response. 

Hence I tried to modified NetworkBoundResource class but unfortunately i can't set result of network response.

**result.setValue(Resource.success(response.body)); // Error on this line**

    private final AppExecutors appExecutors;
    private final MediatorLiveData<Resource<ResultType>> result = new MediatorLiveData<>();

    @MainThread
    NetworkBoundResource(AppExecutors appExecutors) {
        this.appExecutors = appExecutors;
        result.setValue(Resource.loading(null));
        fetchFromNetwork();
    }

    private void fetchFromNetwork() {
        LiveData<ApiResponse<RequestType>> apiResponse = createCall();
        result.addSource(apiResponse, response -> {
            result.removeSource(apiResponse);
            //noinspection ConstantConditions
            if (response.isSuccessful()) {
                appExecutors.diskIO().execute(() -> {
                    saveCallResult(processResponse(response));
                });
                result.setValue(Resource.success(response.body)); // Error on this line
            } else {
                onFetchFailed();
            }
        });
    }

    @WorkerThread
    protected abstract void saveCallResult(@NonNull RequestType item);

    @WorkerThread
    protected RequestType processResponse(ApiResponse<RequestType> response) {
        return response.body;
    }

    @NonNull
    @MainThread
    protected abstract LiveData<ApiResponse<RequestType>> createCall();

    protected void onFetchFailed() {
    }

    public LiveData<Resource<ResultType>> asLiveData() {
        return result;
    }

My Repo code.
    
public LiveData<Resource<ShowMoreFilterResponse>> loadShowMoreFilters() {
        return new NetworkBoundResource<ShowMoreFilterResponse, ShowMoreFilterResponse> (executors) {

            @Override
            protected void saveCallResult(@NonNull ShowMoreFilterResponse item) {
                Timber.i("Saurabh: " + item);
            }

            @NonNull
            @Override
            protected LiveData<ApiResponse<ShowMoreFilterResponse>> createCall() {
                return services.getShowmoreFilters();
            }
        }.asLiveData();
    }

My view model

mFilters = repository.loadShowMoreFilters();

**Comment by ianhanniballake** [comment]
Consider look at [Store](https://blogs.dropbox.com/tech/2020/01/store-grand-re-opening-loading-android-data-with-coroutines/), which seeks to cover the repository pattern, encapsulating the loading state logic.
