### ISSUE TITLE
Paging sample, room, Dependency injection

### ISSUE THREAD

**Issue by klaszlo8207** [android/architecture-components-samples#389]
https://github.com/googlesamples/android-architecture-components/blob/0c2e39d084cbc4ad082e701e0c6a8ff29a3aa737/PagingSample/app/src/main/java/paging/android/example/com/pagingsample/CheeseDb.kt

This class says: 

/**
 * Singleton database object. Note that for a real app, you should probably use a Dependency
 * Injection framework or Service Locator to create the singleton database.
 */

So originally why not used the DI in the sample as well? How can I modificate this code to achieve that?
Is it a very bad way to use this class in this way, like in the sample?

Also the "google sample" is a bad practise? :(

**Comment by ianhanniballake** [comment]
The `GithubBrowserSample` is the more complicated sample that brings together the individual libraries together in one cohesive sample. The other samples are dedicated to one specific API surface (such as Paging) and purposefully focus on that specific area.
