### ISSUE TITLE
Paging sample update list after add/remove item

### ISSUE THREAD

**Issue by klaszlo8207** [android/architecture-components-samples#390]
https://github.com/googlesamples/android-architecture-components/tree/0c2e39d084cbc4ad082e701e0c6a8ff29a3aa737/PagingSample

It is a viewmodel and a recyclerview and also room.

I can add/remove items from the list, but when I add some item, the list doesn't refreshing, just after I scrolling. Any way to refresh the recyclerview's state to invalidate the new items?

**Comment by CarGuo** [comment]
try pagelist?.dataSource?.invalidate()

**Comment by klaszlo8207** [comment]
Thanks, I will try it

**Comment by ianhanniballake** [comment]
The source of truth is Room, so changing your data in Room will automatically invalidate your list and remove items that are removed. The `CheeseDb` is built for static data, so you'd need to add an add and remove method there.

**Comment by clauub** [comment]
> The source of truth is Room, so changing your data in Room will automatically invalidate your list and remove items that are removed. The `CheeseDb` is built for static data, so you'd need to add an add and remove method there.

So if only update data from Room Database that should be fine, right ?

**Comment by dlam** [comment]
> > The source of truth is Room, so changing your data in Room will automatically invalidate your list and remove items that are removed. The `CheeseDb` is built for static data, so you'd need to add an add and remove method there.
> 
> @ianhanniballake  So if only update data from Room Database that should be fine, right ?

@clauub yes!
