### ISSUE TITLE
ViewModel / LiveData in a CanvasWatchFaceService (WearOS)

### ISSUE THREAD

**Issue by NicolasSimon** [android/architecture-components-samples#395]
Hi there,

quick question and/or feature request, but how would one implement ViewModel and LiveData from a CanvasWatchFaceService?

On WearOS, your UI is controlled via a service, and having a way to get the latest data at any given point through LiveData would be pretty beneficial.

However, 

`ViewModelProviders.of(this, viewModelFactory)
                .get(TeamsViewModel::class.java)`

is simply not feasible

> None of the following functions can be called with the arguments supplied: 
@NonNull @MainThread public open fun of(@NonNull p0: Fragment, @Nullable p1: ViewModelProvider.Factory?): ViewModelProvider defined in android.arch.lifecycle.ViewModelProviders
@NonNull @MainThread public open fun of(@NonNull p0: FragmentActivity, @Nullable p1: ViewModelProvider.Factory?): ViewModelProvider defined in android.arch.lifecycle.ViewModelProviders

Any suggestion?

Thanks!

**Comment by ianhanniballake** [comment]
Services would not have `ViewModel` (as they do not go through configuration changes).

You can certainly use [ServiceLifecycleDispatcher](https://developer.android.com/reference/androidx/lifecycle/ServiceLifecycleDispatcher) to help implement `LifecycleOwner` in your Service, which would let you use `LiveData`.
