### ISSUE TITLE
Room SQLiteConnectionPool leakage

### ISSUE THREAD

**Issue by freddyaot** [android/architecture-components-samples#396]
Room doesn't close connection pool. 
After some background requests the logcat print the following warning message:

`W/SQLiteConnectionPool: A SQLiteConnection object for database '%DATABASE_NAME%' was leaked!  Please fix your application to end transactions in progress properly and to close the database when it is no longer needed.`

Current Room version:

`implementation 'android.arch.persistence.room:runtime:1.1.1-rc1'`
` annotationProcessor "android.arch.persistence.room:compiler:1.1.1-rc1`

**Comment by osvalr** [comment]
This issue still persist for the same version

**Comment by svenjacobs** [comment]
Same issue here. Neither the documentation nor the sample applications explain/depict how and when the Room database instance should be closed.

**Comment by svenjacobs** [comment]
As it turns out the `RoomDatabase` must/should not be closed manually. The solution is to keep only one instance of the database in your application, for example in a static field in your `Application` class or managed via an dependency injection framework.

The leak warning will only occur if you for example open multiple database instances (for example one instance in each `Activity`) and don't close them.

**Comment by dlo** [comment]
I'm running into this issue as well.

**Comment by svenjacobs** [comment]
> I'm running into this issue as well.

@dlo See the solution which I described above.

**Comment by Shubhamsdr3** [comment]
@svenjacobs  I have used dependency injection, still getting the same issue.

**Comment by svenjacobs** [comment]
> @svenjacobs I have used dependency injection, still getting the same issue.

If you use DI, make sure that the `RoomDatabase` instance is a singleton which bound to the application lifecycle.

**Comment by ianhanniballake** [comment]
This doesn't seem to be an issue with the samples. You can file an issue against Room on [the issue tracker](https://issuetracker.google.com/issues/new?component=413107) if you're still having an issue.
