### ISSUE TITLE
[Question] How to represent nested Many to One Relationship using Repository pattern in GithubBrowserSample

### ISSUE THREAD

**Issue by Jendrekpl** [android/architecture-components-samples#398]
User can has ONE Car, but Car can have MULTIPLE Users. 

public class User {
  public int id;
  public Car car;
}

public class Car {
  public int id;
  public String carName;
}

How to write entity for something like that?
How to write UserDao to save User and his Car and when I get User I get his Car too?

**Comment by ianhanniballake** [comment]
This issue doesn't seem directly related to the samples here. Consider posting to StackOverflow with what you've tried.
