### ISSUE TITLE
Paging Library, RxJava2

### ISSUE THREAD

**Issue by daimonkor** [android/architecture-components-samples#403]
@florina-muntenescu, please provide sample Paging RxJava2, there are problems with hot or cold observables and reseting recyclerview after rotate device.
I tried to refactor https://github.com/erikcaffrey/Movies-PagingLibrary-Arch-Components sample
my sample https://www.dropbox.com/sh/40x772wgxawr2lg/AADECVHVVZqZIdg507SjFF4Ka?dl=0

Thanks for you support.

**Comment by ianhanniballake** [comment]
There's no plans on providing a Paging + RxJava2 sample, sorry.
