### ISSUE TITLE
Unit test for Lifecycle Event

### ISSUE THREAD

**Issue by gokhanaliccii** [android/architecture-components-samples#406]
How can we create a unit test for a function which is running with annotated lifecycle event. (Before send this issue I have already asked this question at [stackoverflow](https://stackoverflow.com/questions/51099003/how-can-i-add-unit-test-for-android-architecture-components-life-cycle-event), but I didn't get answer.) 

    public class CarServiceProvider implements LifecycleObserver {

      public void bindToLifeCycle(LifecycleOwner lifecycleOwner) {
         lifecycleOwner.getLifecycle().addObserver(this);
      }

      @OnLifecycleEvent(Lifecycle.Event.ON_STOP)
      public void onClear() {
         Log.i("CarServiceProvider", "onClear called");
      }
    }

**Comment by ianhanniballake** [comment]
Looks like you've gotten some good answers on your StackOverflow question.
