### ISSUE TITLE
BoundaryCallback.onItemAtEndLoaded not always got called in a ContiguousPagedList

### ISSUE THREAD

**Issue by LanderlYoung** [android/architecture-components-samples#410]
this is a repost of google issue tracker https://issuetracker.google.com/issues/111187234

Component used: PagingLibrary
Version used: 1.0.1
Devices/Android versions reproduced on: N/A

If this is a bug in the library, we would appreciate if you could attach:
- Sample project to trigger the issue.
- A screenrecord or screenshots showing the issue (if UI related).

I was using PageKeyedDataSource, in my scenario when the last page is loaded, server returns a flag to indicate the end of paging, and the "next page key" be null.

For instance, I have 20 items, each page got 10 items, the request looks like this,

Load Initial(page 0):
 pageKey: null
 result: list[10]
 nextPageKey: "balabala"
 isEndOfPaging: false

Load After(page 1):
 pageKey: "balabala"
 result: list[10]
 nextPageKey: null
 isEnfOfPaging: true

When "page 1" is returned by the LoadCallback, there are no more loadAfter calls, which means the ContiguousPagedList already knows it's "end of page" signal. 

However, the ContiguousPagedList did not fire a boundary callback; it's hardcoded that "deferEnd" be true only if "pageResult.page.size()" is 0, which is not my case.

code in ContiguousPagedList: 

```kotlin
fun onPageResunt(...) {
    boolean deferEmpty = mStorage.size() == 0;
    boolean deferBegin = !deferEmpty
            && resultType == PageResult.PREPEND
            && pageResult.page.size() == 0;
    boolean deferEnd = !deferEmpty
            && resultType == PageResult.APPEND
            && pageResult.page.size() == 0;
    deferBoundaryCallbacks(deferEmpty, deferBegin, deferEnd);
}
```

sample DataSource Implementation can be like this:
```kotlin
class DemoDataSource : PageKeyedDataSource<Int, String>() {
    override fun loadInitial(params: LoadInitialParams<Int>, callback: LoadInitialCallback<Int, String>) {
        val result = (0 until 10).map { it.toString() }
        callback.onResult(result, null, 10)
    }

    override fun loadAfter(params: LoadParams<Int>, callback: LoadCallback<Int, String>) {
        val key = params.key!!
        val result = (key until (key + 10)).map { it.toString() }
        
        // we got no more pages
        val nextPageKey :Int? = null
        
        callback.onResult(result, nextPageKey)
    }

    override fun loadBefore(params: LoadParams<Int>, callback: LoadCallback<Int, String>) {
        TODO("no-op")
    }
}
```

**Comment by dlam** [comment]
The issue linked here is actually fixed - so closing this while doing some cleanup of our github issues :smile:
