### ISSUE TITLE
Expose page load status in a PagedList.

### ISSUE THREAD

**Issue by LanderlYoung** [android/architecture-components-samples#411]
this is a repost of google issue tracker https://issuetracker.google.com/issues/111146172

Component used: PagingLibrary
Version used: 1.0.1
Devices/Android versions reproduced on: N/A

This is a feature request:
consider expose page load statue (fully loaded, partially loaded, empty list, etc...) 

Currently, we can only use BoundaryCallback to achieve this purpose, which is a little bit complicated(and according to Architecture demo, this is not what BoundaryCallback designed to do). We should use a BooundaryCallbak when building PagedList with LivePagedListBuilder, and expose such statue with a liveData inside the viewModel.

If it's provided by PagedList and UI logic just observe PagedList, that would be more elegant.

**Comment by ianhanniballake** [comment]
The issue tracker is the correct place for feature requests for Paging. Thanks for filing an issue!
