### ISSUE TITLE
Export and import room database

### ISSUE THREAD

**Issue by prabinshrestha** [android/architecture-components-samples#423]
I need in my application to export and import database.it works fine while using traditional approach : copying database to some file in android file system and vice versa (export and import) but room is missing some data of some table (incomplete row).Is there any good solution?

**Comment by or-dvir** [comment]
i am also in need of exporting and importing room db in my app. also a bunch of people here https://github.com/googlesamples/android-architecture-components/issues/340
in the meantime i seem to be able to copy existing db to file system, but i am stuck on importing it back.
can you please share your code on how you did it?

**Comment by ianhanniballake** [comment]
This doesn't seem to be an issue with the samples. You can file an issue against Room on [the issue tracker](https://issuetracker.google.com/issues/new?component=413107) if you're still having an issue.

**Comment by hasnain-ahmad** [comment]
> This doesn't seem to be an issue with the samples. You can file an issue against Room on [the issue tracker](https://issuetracker.google.com/issues/new?component=413107) if you're still having an issue.

I have posted the at the following link.
https://issuetracker.google.com/issues/154588984
