### ISSUE TITLE
关于vIewModel的疑问，希望解答 （Questions about vIewModel, I hope to answer）

### ISSUE THREAD

**Issue by zhangtuodd** [android/architecture-components-samples#424]
中文描述 ： 
研读了一天关于architecture-components的库，对viewModel有一个疑问。描述如下：viewModel保存的数据可以独立于Activity之外，也就是说当Activity销毁后viewModel保存的数据还存在(根据屏幕旋转的例子可以看出，旋转屏幕后Activity实例已经重新创建，但viewModel实例还是原来的)，但是当我ActivityA跳转到ActivityB后，再从ActivityB用Intent方式跳转到ActivityA，viewModel却重新创建了导致UI显示错误(在跳转和屏幕旋转前，我更新了ViewModel的数据)，我觉得跳转方式和屏幕旋转方式并没有区别，然而viewModel却变了。
这个疑问困惑我很久，很着急，我不确定操作方式是否有问题，烦请解答！
English description ： 
I studied the library of architecture-components for one day and had a question about viewModel. The description is as follows: The data saved by the viewModel can be independent of the Activity, that is to say, the data saved by the viewModel still exists after the Activity is destroyed. (According to the example of the screen rotation, the Activity instance has been re-created after rotating the screen, but the viewModel instance is still The original), but when I jumped from ActivityA to ActivityB, and then jumped from ActivityB to ActivityA with Intent, the viewModel was recreated and caused the UI display error (I updated the ViewModel data before the jump and screen rotation). ), I think there is no difference between the jump mode and the screen rotation mode, but the viewModel has changed.
This question has puzzled me for a long time,  very anxious, I am not sure if there is a problem with the operation method, please answer!

**Comment by rayworks** [comment]
> 我觉得跳转方式和屏幕旋转方式并没有区别

See also the [docs](https://developer.android.google.cn/guide/components/activities/tasks-and-back-stack#ManagingTasks).

**Comment by SunBerwin** [comment]
你以为你以为的就是你以为的吗

在2018年07月30日 10:36，rayworks<notifications@github.com><mailto:notifications@github.com> 写道：

我觉得跳转方式和屏幕旋转方式并没有区别

See also the docs<https://developer.android.google.cn/guide/components/activities/tasks-and-back-stack#ManagingTasks>.

**Comment by ianhanniballake** [comment]
Generally, starting an Activity using an Intent will create a new instance of an Activity. That new Activity instance will have its own ViewModels.
