### ISSUE TITLE
Provide a Java Branch for GithubBrowserSample

### ISSUE THREAD

**Issue by feinstein** [android/architecture-components-samples#432]
I can see the GithubBrowserSample was at first written in Java and has been converted to Kotlin.

Could you please make a branch where the code is been updated and fixed in Java? I honestly don't intend to learn Kotlin with Flutter being so promising. Thanks!

**Comment by mynormeza** [comment]
I've been waiting for the Java version of GithubBrowserSample too. And feel the same, I won't be learning Kotlin in a near future

**Comment by mynormeza** [comment]
I found it. Thanks
