### ISSUE TITLE
Gradle library dependencies new version lint

### ISSUE THREAD

**Issue by XabierGoros** [android/architecture-components-samples#439]
I'm aware this question is not a particular issue of any sample, but because of I'm seeing all your sample projects follow the same pattern for handling libraries versioning by using another gradle file called `versions.gradle`. This pattern is actually very nice (IMHO even nicer the pure Kotlin/buildSrc version with auto-completion), however using this cleaner approach in Android Studio the new version lint is no longer available.

Am I missing anything or is there any way to make that feature work?

**Comment by ianhanniballake** [comment]
Feel free to [file a bug against Lint](https://issuetracker.google.com/issues/new?component=192718) if you'd like to see this supported. Right now, the Lint only works if you have the artifact group / name in the `dependencies` block (i.e., you can have the versions in a `versions.gradle`, but not the `deps` block approach).
