### ISSUE TITLE
Can't build PagingWithNetworkSample

### ISSUE THREAD

**Issue by feinstein** [android/architecture-components-samples#440]
When I try to build the PagingWithNetworkSample I get the following gradle error:

> Configuration on demand is not supported by the current version of the Android Gradle plugin since you are using Gradle version 4.6 or above. Suggestion: disable configuration on demand by setting org.gradle.configureondemand=false in your gradle.properties file or use a Gradle version less than 4.6.

I didn't any modifications on the code, I just downloaded it and I am running the most recent version of Android Studio (3.1.4)

**Comment by ianhanniballake** [comment]
Seems to work fine now.
