### ISSUE TITLE
PagingRequestHelper Concurrency bug

### ISSUE THREAD

**Issue by feinstein** [android/architecture-components-samples#445]
The `PagingRequestHelper` method `runIfNotRunning` has at its beginning:

    boolean hasListeners = !mListeners.isEmpty();

This is outside the synchronization block, and there isn't any synchronizations in the add and remove listener methods. 

The `mListener` is a `CopyOnWriteArrayList<Listener>`, which means that whenever there is a mutating operation in the list, a new list will be created, this prevents many concurrency issues, but (as far as I know) will not prevent synchronization issues.

So, `hasListeners` could evaluate to `false` in the begging of the method, then another thread could add a listener to the list, the list will be copied internally but `hasListeners` will still be `false` despite the fact that there is now a listener waiting to be called, and won't be called.

There must be synchronization between `hasListeners` loading/uses and the add/remove listeners.

**Comment by jQrgen** [comment]
Is this still a thing? How to use paging without PagingRequestHelper.java?

**Comment by dlam** [comment]
Paging3's release has made `PagingRequestHelper` obsolete as Errors and LoadState are now officially supported as part the library. A `PagingSource` can notify a `PagingDataAdapter` / `AsyncPagingDataDiffer` of recoverable errors by returning `LoadResult.Error` and `PagingDataAdapter` / `AsyncPagingDataDiffer` now have APIs to `retry()` errors and listen to LoadState updates via `.loadStateFlow.collectLatest { ... }` and `.addLoadStateListener { combinedLoadStates -> ... }`
