### ISSUE TITLE
Room Concurrency

### ISSUE THREAD

**Issue by SeniorZhai** [android/architecture-components-samples#452]
I use LiveData to my project with Room,when my database is so large.
Some sql is slow(a few seconds)，when it executing, LiveData is not working.
And multiple sql insert ，LiveData also not working.

**Comment by SeniorZhai** [comment]
https://github.com/aosp-mirror/platform_frameworks_support/blob/d79202da157cdd94c2d0c0b6ee57170a97d12c93/room/runtime/src/main/java/androidx/room/InvalidationTracker.java#L336
I think sql is slow, InvalidationTracker mRefreshRunnable will no longer be updated

**Comment by ianhanniballake** [comment]
This doesn't seem to be an issue with the samples. You can file an issue against Room on [the issue tracker](https://issuetracker.google.com/issues/new?component=413107) if you're still having an issue.
