### ISSUE TITLE
How should I use ViewModel in a single Activity application?

### ISSUE THREAD

**Issue by tonycheng93** [android/architecture-components-samples#462]
How should I use ViewModel in a single Activity application? My app has only one activity，and no fragment.My app is based on Views,just llike [Conductor](https://github.com/bluelinelabs/Conductor).How can I use ViewModel in a single Activity framework?

**Comment by pablichjenkov** [comment]
You can use one instance of android architecture ViewModel as a Holder for other instances of your own ViewModel class. Google named this class ViewModel but I would only use it with the purpose of surviving orientation and other configuration changes.
What I would do is create a ViewState class, this will have the data/state of my Views(ViewGroups, Fragments). Then I would have only one instance of the architecture components ViewModel, I would name it **configurationChangesPersister** or something like that. Then this unique instance will have the a Collection of ViewState instances. 
Then I would create some interface to access this **configurationChangesPersister** from any Fragment or ViewGroup that is attached to the Activity. So the Single Activity will be a ViewState provider or something like that. 
Here is an example of the idea:
https://github.com/pablichjenkov/Voltus
https://github.com/pablichjenkov/Reactive-Wrokflow

You can also not use the architecture ViewModel at all and declare your ViewState container at application level. That way they will survive configuration changes as well.

**Comment by murageden** [comment]
You can use ViewModel to update your UI once data in your data store changes, probably due to user interaction on the UI. Consider[ViewModel](https://developer.android.com/topic/libraries/architecture/viewmodel) as a quick way to manage how UI interactions make changes to your data store and seamlessly transform the UI based on those changes.

**Comment by ianhanniballake** [comment]
Navigation 2.2.0 or higher allows you to [access a ViewModel at the destination level](https://developer.android.com/guide/navigation/navigation-programmatic#navbackstackentry).

Navigation was specifically built to support any kind of destination, including [hooking into systems such as Conductor](https://medium.com/prolific-interactive/navigating-conductor-and-the-navigation-architecture-component-4145b5ad9bcf). You can certainly adapt that code to more recent versions of Navigation and get full support for `Lifecycle`, `ViewModel`, and other Architecture Components while still using Conductor.
