### ISSUE TITLE
Delete PagedList Item (Network + DB)

### ISSUE THREAD

**Issue by Dilip23** [android/architecture-components-samples#467]
No clear understanding of deleting a pagedlist item which is backed by room and network api
When and where to invalidate?

**Comment by dlam** [comment]
Room generates a `DataSource.Factory` implementation which loads data from a provided `@Query`.

You can simply delete the row in your db and Room will automatically propagate invalidation to the DataSource, which pushes a new PagedList / Datasource pair to represent the updated data.
