### ISSUE TITLE
BUILD FAILD

### ISSUE THREAD

**Issue by stAyushJain** [android/architecture-components-samples#489]
After updating Room to (2.0.1-alpha01) I am getting error.
ERROR -> Android dependency 'androidx.arch.core:core-runtime' has different version for the compile (2.0.0) and runtime (2.0.1-alpha01) classpath. You should manually set the same version via DependencyResolution

Dependecies: 
 implementation 'androidx.lifecycle:lifecycle-runtime:2.0.0'
 implementation 'androidx.lifecycle:lifecycle-extensions:2.0.0'
kapt 'androidx.lifecycle:lifecycle-compiler:2.0.0'

implementation 'androidx.room:room-runtime:2.0.1-alpha01'
kapt: 'androidx.room:room-compiler:2.0.1-alpha01'
 implementation 'androidx.room:room-rxjava2:2.0.1-alpha01'

**Comment by ianhanniballake** [comment]
This doesn't seem like an issue with these samples. Consider using StackOverflow or filing an issue against Room on [the issue tracker](https://issuetracker.google.com/issues/new?component=413107) if you're still having an issue.
