### ISSUE TITLE
Flowable + Room query single should emit onNext or onError instead of complete silence

### ISSUE THREAD

**Issue by namdp** [android/architecture-components-samples#490]
1. Query single item -> When there is no record in the database and the query returns no rows, the Flowable will not emit, neither onNext, nor onError. (We need handle no record in some case -> should return empty value or error instead)
2. Query single item -> When there is no record in the database Flowable return an empty list

**Comment by ianhanniballake** [comment]
This doesn't seem to be an issue with the samples. You can file an issue against Room on [the issue tracker](https://issuetracker.google.com/issues/new?component=413107) if you're still having an issue.
