### ISSUE TITLE
Room database - Error: Code too large

### ISSUE THREAD

**Issue by HimanshuDudhat** [android/architecture-components-samples#492]
I have added around  90 tables with it's relations, during compilation compiler gives below error

```
\db\AppDatabase_Impl.java:393: error: code too large 
protected void validateMigration(SupportSQLiteDatabase _db) { 
^ 
Note: Some input files use or override a deprecated API. 
Note: Recompile with -Xlint:deprecation for details. 
1 error 
:app:compileDebugJavaWithJavac FAILED 
:app:buildInfoGeneratorDebug 

FAILURE: Build failed with an exception. 

* What went wrong: 
Execution failed for task ':app:compileDebugJavaWithJavac'. 
> Compilation failed; see the compiler error output for details.
(see full text)
```

this method has around 4k line of generated code

**Comment by DoubleF1re** [comment]
Same issue when you have many @Embedded objects in @Entity. Error thrown by java compiler what code and code in try statement too large. The problem is what method in _impl.class not splitted up into several methods.

**Comment by ianhanniballake** [comment]
This doesn't seem to be an issue with the samples. You can file an issue against Room on [the issue tracker](https://issuetracker.google.com/issues/new?component=413107) if you're still having an issue.

**Comment by tatavarthitarun** [comment]
any update?
