### ISSUE TITLE
The MVVM pattern needs to be confused. I decompile the app and found that the class using 'variable' in the layout is not confusing. Ask for answers! !

### ISSUE THREAD

**Issue by l-w-h** [android/architecture-components-samples#515]
## The MVVM pattern needs to be confused. I decompile the app and found that the class using 'variable' in the layout is not confusing. Ask for answers! !
<pre>
    buildTypes {
        release {
           …
            minifyEnabled true
            zipAlignEnabled true
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
            …
        }
        …
    }
</pre>

**Comment by ianhanniballake** [comment]
It isn't clear what you're asking. Feel free to file a new issue with a full explanation of what you're seeing and what you expect to see if you're still having an issue.
