### ISSUE TITLE
Callback about model is initiated

### ISSUE THREAD

**Issue by emartynov** [android/architecture-components-samples#535]
I have a question about the design of the ViewModel class.

It is a well known rule of thumbs do not call any open methods or start threads within the constructor.

However, since we don't have a callback for this in the ViewModel (in comparing to `onCleared()`) we have to start some things in the init block or have boolean guards to prevent starting the same thing twice.

It would be great to have a callback that will allow initing things once while the model is instantiated or attached the first time.

Let me know what do you think.

**Comment by ianhanniballake** [comment]
This doesn't seem to be an issue with the samples. Please file a feature request against Lifecycle on [the issue tracker](https://issuetracker.google.com/issues/new?component=413132) if you'd still like this.
