### ISSUE TITLE
Migration  without schema change

### ISSUE THREAD

**Issue by fariz-sirajli** [android/architecture-components-samples#538]
Hello. In my application i use ready database file,  put it in assests folder. When i open app i copy it to corresponding folder and use it with Room. 
So my question is do i need to add migration when i update app in play store? In every update, i only add new data to tables and do not change schema.
I get  java.lang.IllegalStateException: attempt to re-open an already-closed object from my crash report and now try to find reason.
Thanks for attention

**Comment by thirtyyuan** [comment]
Maybe your SQL of migration is incorrect. Can you find another error description about like below: 
![](https://ws2.sinaimg.cn/large/006tNc79ly1fzafms78btj31de04et9v.jpg), if yes, you can 「find」the correct SQL in this file Or [migration_num].json, like: Migration_1_2, you can find it in 2.json.

**Comment by thirtyyuan** [comment]
Using the action of `Find` which is Navigating and searching within Android Studio, or the path of the file is `YourModule/build/generated/source/apt/debug/YourPackageName.YourDatabaseName_Impl.java`

**Comment by ianhanniballake** [comment]
This doesn't seem to be an issue with the samples. You can file an issue against Room on [the issue tracker](https://issuetracker.google.com/issues/new?component=413107) if you're still having an issue.
