### ISSUE TITLE
onItemAtEndLoaded(itemAtEnd: Any) returns first element

### ISSUE THREAD

**Issue by BulatMukhutdinov** [android/architecture-components-samples#547]
I am implementing paged list using PagedList.BoundaryCallback. I need to load next page based on last loaded item in a list. Callback for this is onItemAtEndLoaded(itemAtEnd: T). But why itemAtEnd is the first item of PagedList? It should be last item of PagedList

**Comment by dlam** [comment]
Sorry that we never got to this - the issues here are mainly for the samples, the best way to get traction on an issue / question with the library is to file a bug against our issuetracker at: https://issuetracker.google.com/issues/new?component=413106&template=1096385

However the v2 API `PagedList.BoundaryCallback` has been superseded by `RemoteMediator` in v3, and realistically there won't be any more work on the v2 APIs as v3 approaches a stable release.
