### ISSUE TITLE
Logic of refresh user data in GithubBrowserSample

### ISSUE THREAD

**Issue by aL05flas** [android/architecture-components-samples#556]
Hello! How implements force refresh user data from network if user click on refresh button?
Call from UI passed to Viewmodel, after passed to Repository.. But how update LiveData of concrete user by ApiResponse and Resource state (like Loading..)? How link loading from network concrete user with LiveData that hold in ViewModel and observed in UI?

**Comment by ianhanniballake** [comment]
Room has added support for [prepopulating the database](https://developer.android.com/training/data-storage/room/prepopulate), which does not suffer from these types of issues, whether you use `LiveData` or not.

**Comment by ianhanniballake** [comment]
This is precisely the use case for [Store](https://blogs.dropbox.com/tech/2020/01/store-grand-re-opening-loading-android-data-with-coroutines/), an implementation of the repository pattern that has specific support for loading states and busting through the cache.
