### ISSUE TITLE
Foreign Key is Room

### ISSUE THREAD

**Issue by Wajahat-Jawaid** [android/architecture-components-samples#560]
Hi, I just wanted to know if null or an unknown value can be inserted in the Foreign key?
The need is I want to insert the records whose value for foreign key is not yet decided.

Thanks!

**Comment by YassinAJDI** [comment]
SQLite does support NULL values as Foreign key. So yes Room will be able to handle it.

**Comment by ianhanniballake** [comment]
This doesn't seem be an issue with the samples. You can file an issue against Room on [the issue tracker](https://issuetracker.google.com/issues/new?component=413107) if you still have a question / feature request.
