### ISSUE TITLE
GithubBrowserSample fullCoverageReport produces empty report.

### ISSUE THREAD

**Issue by AradiPatrik** [android/architecture-components-samples#561]
I cloned the repository then ran .\gradlew fullCoverage and the build\reports\jacoco\fullCoverageReport\html\index.html shows empty coverage report.

I suspect that the problem is that:
```
executionData = fileTree(dir: "$buildDir", includes: [
            "jacoco/testDebugUnitTest.exec",
            "outputs/code-coverage/connected/*coverage.ec"
    ])
```
is at fault, because I don't have outputs/code-coverage folder, instead I have outputs/code_coverage/debugAndroidTest/connected/*coverage.ec
I am on
Android Studio 3.3.1
Build #AI-182.5107.16.33.5264788, built on January 29, 2019
JRE: 1.8.0_152-release-1248-b01 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by ianhanniballake** [comment]
See #752
