### ISSUE TITLE
Deep link with multiple query parameters

### ISSUE THREAD

**Issue by BulatMukhutdinov** [android/architecture-components-samples#585]
Env: navigation 2.0.0-rc02
In a navigation graph, if I register deep link like this
```
<deepLink app:uri="scheme://path/arq?arg={arg}" />
```
It redirects me to a targetted fragment
but if I declare multiple args like this
```
<deepLink app:uri="scheme://path/arq?arg1={arg1}&amp;arg2={arg2}" />
```
It is handled by activity's onNewIntent(). Expected behavior that it redirects me also to desired fragment.

P.S.  I can read all the values from intent.data but if I am calling 
```
findNavController(R.id.hostFragment).handleDeepLink(intent)
```
it still says that there are no deep links

**Comment by xyzira** [comment]
It's the issue with the adb command: add "\" before "&":
https://stackoverflow.com/a/35645448/727768

**Comment by ianhanniballake** [comment]
This doesn't seem to be an issue with the samples. Please file an issue against Navigation on [the issue tracker](https://issuetracker.google.com/issues/new?component=409828).
