### ISSUE TITLE
I use PeriodicWorkRequest not working properly

### ISSUE THREAD

**Issue by yinjinyj** [android/architecture-components-samples#587]
WorkManager.getInstance().getWorkInfosByTagLiveData("YIN").observe(this, Observer {
            if (it?.get(0)?.outputData?.keyValueMap?.isEmpty() == true) {
                return@Observer
            }
            Toast.makeText(this, it?.get(0)?.outputData?.getString(SimpleTwoWorker.TWO_WORKER_NAME), Toast.LENGTH_LONG).show()
        })
        WorkManager.getInstance().enqueue( PeriodicWorkRequestBuilder<SimpleTwoWorker>(300, TimeUnit.MILLISECONDS, 300, TimeUnit.MILLISECONDS)
            .addTag("YIN")
            .setConstraints(Constraints.Builder().setRequiredNetworkType(NetworkType.NOT_REQUIRED).build())
            .setInputData(workDataOf(SimpleTwoWorker.TWO_WORKER_SUCCESS to true))
            .build())

class SimpleTwoWorker : Worker {
    override fun doWork(): Result {
        Log.e("SimpleTwoWorker","doWork")
        return if (inputData.getBoolean(TWO_WORKER_SUCCESS, false)) {
            Result.success(workDataOf(TWO_WORKER_NAME to "TWO_YIN", TWO_WORKER_AGE to 50))
        } else {
            Result.failure(workDataOf(TWO_WORKER_FAIL to "TWO_FAIL"))
        }
    }

    constructor(context: Context, parameters: WorkerParameters) : super(context, parameters)

    companion object {
        const val TWO_WORKER_SUCCESS = "TWO_WORKER_SUCCESS"
        const val TWO_WORKER_NAME = "TWO_WORKER_NAME"
        const val TWO_WORKER_AGE = "TWO_WORKER_AGE"
        const val TWO_WORKER_FAIL = "TWO_WORKER_FAIL"
    }
}

this is my code ,i use my phone to  test ，i find the callback normal execution and specified interval not execution and the result livedata not observe 

i hope get the answer 
thinks

**Comment by ianhanniballake** [comment]
This doesn't seem to be an issue with the samples. Please file issues against WorkManager on [the issue tracker](https://issuetracker.google.com/issues/new?component=409906) if this is still an issue.
