### ISSUE TITLE
How to add new items to a pagedList backed by Room

### ISSUE THREAD

**Issue by roshanthejoker** [android/architecture-components-samples#595]
I am using Network + Database for pagination in my app. I have 2 model classes that extends same types. Only one type of model is backed by Room Database. I want to inject other model class in between the pagedlist based on some business rules. When I try to do that ny using mapByPage function on Datasource.Factory returned by Room. The paging lib is throwing IllegalStateExeception with message that size has changed. How do I go about implementingt this case? Any help is appreciated.

**Comment by ianhanniballake** [comment]
See [this issue](https://issuetracker.google.com/issues/147833132) for how Paging/RecyclerView is going to handle adding headers/footers/other types of data.
