### ISSUE TITLE
Question: About the Fragment instances！

### ISSUE THREAD

**Issue by yang0range** [android/architecture-components-samples#601]
1.When I create a new Destination, I have to create a new Fragment instances, regardless of whether I created it before?
Must repeat the onCreateView onActivityCreated methods?

2.Can Fragment be reused?If so, how will I do it?

**Comment by ianhanniballake** [comment]
Navigation only keeps fragments that are on the back stack. Adding a new Fragment to the back stack (i.e., `navigate` to a new destination) will always create a new instance.

**Comment by yang0range** [comment]
if i want do not back stack,how can i do ?

**Comment by ianhanniballake** [comment]
You can [pop other destinations off the back stack](https://developer.android.com/guide/navigation/navigation-navigate#pop).

**Comment by yang0range** [comment]
if i want  reuse this fragment ? how can i do？
Thanks.
