### ISSUE TITLE
Get query params in respective fragment : Navigation Component

### ISSUE THREAD

**Issue by Vissonabe** [android/architecture-components-samples#602]
Env: navigation 2.0.0
In a navigation graph, I registered deep link like this

<deepLink app:uri="scheme://path/view" />

if i get deeplink as "scheme://path/view"
It redirects me to a targeted fragment

but if I get deeplink like this
"scheme://path/view?key=value"
"scheme://path/view?key=value&key1=value1"
"scheme://path/view?key=value&key2=value2"
"scheme://path/view?key2=value2"

Actual:
it is not directing the the targeted fragment. How to read all the query params that are passed.

Expection:
it should navigate to the targetted fragment and should be able to read all the query params in
argument in targeted fragment.

**Comment by ianhanniballake** [comment]
Query parameter support was added in [Navigation 2.2.0](https://developer.android.com/jetpack/androidx/releases/navigation#2.2.0).
