### ISSUE TITLE
two suggestions for Paging Library

### ISSUE THREAD

**Issue by zhangyicoding** [android/architecture-components-samples#623]
Dear Google, here are two suggestions for Paging.
1, I'm using Paging with RxJava, I found RxJava only execute onNext, but not onComplete. I suggest to add 【mEmitter.onComplete()】 code in Paging, then  we can write business code in our own onComplete.
2, when I use Paging with Retrofit, I think the event is not linear, although I use RxJava, I still use callback.onResult(...)  to commit our data, the codes are not graceful,I hope the data from retrofit to Paging can be linear, of course using RxJava.
Thanks very much.

**Comment by zhangyicoding** [comment]
additional, I use the version is "androidx.paging:paging-runtime-ktx:2.1.0"

**Comment by ianhanniballake** [comment]
This doesn't seem to be an issue with the samples. You can file a feature request / issue against Paging on [the issue tracker](https://issuetracker.google.com/issues/new?component=413106).
