### ISSUE TITLE
update entity except some parameters

### ISSUE THREAD

**Issue by luoyexk** [android/architecture-components-samples#624]
I want to update an entity other than a few parameters.

```
@Update
fun updateProject(project: Project)

@Entity(tableName = "projects")
class Project{
var id
var address = ""
var projectName = ""
.
.
↑100 parameters
var test:Boolean? = null
}
```

>class Project has 101 parameters.

When invoke function updateProject(),I only want to update all parameters except test,how can I do it?
I have an idea , override method like this, but it  seems terrible!

```
@Update
fun updateProject(id,address,projectName...100param)
```

second idea,

```
class SonProject: Project{
var test:Boolean? = null
}
@Update
fun updateProject(project: Project)
@Update
fun updateSonProject(sProject: SonProject)
```

>class Project has 100 parameters.
>class SonProject extends Project, it has only one parameter what is test

**Comment by luoyexk** [comment]
seems use foreignKeys can solve it

```
@Entity(tableName = "project_offline",
        foreignKeys = [ForeignKey(entity = Project::class,
                parentColumns = arrayOf("project_id"),
                childColumns = arrayOf("project_id"),
                onDelete = ForeignKey.CASCADE)],
        indices = [Index(value = ["project_id"])]
)
class ProjectOffline(@PrimaryKey
                     @ColumnInfo(name = "project_id")
                     var projectId: Long = 0,
                     @ColumnInfo(name = "offline")
                     var offline: Boolean)
```

**Comment by ianhanniballake** [comment]
This doesn't seem to be an issue with the samples. You can file an issue against Room on [the issue tracker](https://issuetracker.google.com/issues/new?component=413107) if you're still having an issue / feature request.
