### ISSUE TITLE
Duplicate class found for DataBinding on implementation of room

### ISSUE THREAD

**Issue by sangeetagupta2068** [android/architecture-components-samples#626]
On implementation of Room, I am facing a compile time error "Duplicate class found" for data binding on my Android Studio project. The code works individually when I tested both room and data binding separately. Please help. Link to project code : https://github.com/sangeetagupta2068/ExpenseManager

**Comment by zhiwei1990** [comment]
In your `ExpenseItem`.java **all the field** variable should define the `setter` and `getter`
Notice that **itemId** and **itemQuantity** do not implement the setter and getter.

when use `@Entity` in Kotlin all the field should public

**Comment by zhiwei1990** [comment]
> On implementation of Room, I am facing a compile time error "Duplicate class found" for data binding on my Android Studio project. The code works individually when I tested both room and data binding separately. Please help. Link to project code : https://github.com/sangeetagupta2068/ExpenseManager

In your ExpenseItem.java all the field variable should define the setter and getter
Notice that itemId and itemQuantity do not implement the setter and getter.

when use @Entity in Kotlin all the field should public

**Comment by ianhanniballake** [comment]
This doesn't seem to be an issue with the samples. You can file an issue against DataBinding on [the issue tracker](https://issuetracker.google.com/issues/new?component=192721) if you're still having an issue.
