### ISSUE TITLE
PagedListAdapter loads infinite data inside NestedScrollView

### ISSUE THREAD

**Issue by abhishekhugetech** [android/architecture-components-samples#633]
Hello,
I am having a NestedScrollView and inside that, I am having an EditText, a Button and a Recycler View. The problem is that when the activity containing all these items is loaded the PagedListAdapter loads all the data available on the server. This causes the app to show an ANR and in some cases makes the scrolling very laggy.

I tried SmartNestedScrollView but then only a small portion of my recycler view which is visible in scrolls, not the entire container containing all these three views.

**Comment by ianhanniballake** [comment]
This doesn't seem to be an issue with the samples. You can file an issue against RecyclerView on [the issue tracker](https://issuetracker.google.com/issues/new?component=460887) if you're still having an issue.
