### ISSUE TITLE
[NavigationAdvancedSample] Add support ViewPager for swipeable navigationbottomview

### ISSUE THREAD

**Issue by antranvn** [android/architecture-components-samples#646]
After add support ViewPager for swipeable navigationbottomview, is there any way to use nav_host_container in  activity_main, because we need add viewpager in the layout?

**Comment by ianhanniballake** [comment]
As per the [transitions behavior of bottom navigation](https://material.io/components/bottom-navigation/#behavior):

> Avoid using lateral motion to transition between views. Lateral motion is reserved for navigating between peers.

So a `ViewPager` is not appropriate for usage with bottom navigation.
