### ISSUE TITLE
There are multiple good constructors and Room will pick the no-arg constructor. You can use the @Ignore annotation to eliminate unwanted constructors.

### ISSUE THREAD

**Issue by Lumi1717** [android/architecture-components-samples#652]
This error occurred and all of the solutions are for kotlin.
im using java.

My code:
@PrimaryKey (autoGenerate = true )
    private int productId;

    @NonNull
    private int photo;
    private  String name;
    private String description;
    private int price;
    private String gender;
    private String location;
    private String uct;
    private double longi;
    private double latit;
    private String phone;

    @Ignore
    private Bitmap bitmap;
    @Ignore
    private int DB_ID;

**Comment by kouassives** [comment]
Yes, add @Ignore to all the things that are not supposed to be the one that Room has to use.

To consider only the contructor having all the parameters as defined in your database.

Exemple : 


@Entity(tableName = "stops")
public class Stop {
    @PrimaryKey
    @NonNull
    @ColumnInfo(name ="stop_id")
    public int stopId;

    @ColumnInfo(name ="stop_code")
    public int stopCode;

    @ColumnInfo(name ="stop_name")
    public String stopName;

    @ColumnInfo(name = "stop_desc")
    public String stopDesc;

    @ColumnInfo(name = "stop_lat")
    public double stopLattitude;

    @ColumnInfo(name ="stop_lon")
    public double stopLongtitude;

    @ColumnInfo(name ="zone_id")
    public String zoneId;

    @ColumnInfo(name = "stop_url")
    public String stopUrl;

    @ColumnInfo(name ="location_type")
    public String locationType;

    @ColumnInfo(name ="parent_station")
    public String parentStation;

    @ColumnInfo(name ="stop_timezone")
    public String stopTimezone;

    @ColumnInfo(name ="wheelchair_boarding")
    public String wheel_chair;

    @Ignore
    public Stop(){

    }

**Comment by ianhanniballake** [comment]
This doesn't seem to be an issue with the samples. You can file an issue against Room on [the issue tracker](https://issuetracker.google.com/issues/new?component=413107) if you're still having an issue.

**Comment by sud007** [comment]
> It seems like Room and Kotlin versions need to be matched. I have same issue with Room 2.3.0 and Kotlin 1.6.10 but it's ok with kotlin 1.5.20 But it looks ok after I updated Room to 2.4.2 https://youtrack.jetbrains.com/issue/KT-45883

Wow this worked for me! Running old project back to life is really painful! Thank you!

**Comment by Rajeev745** [comment]
Just add the @Ignore annotation on your constructor and it will work
