### ISSUE TITLE
GithubBrowserSample - SearchFragmentDirections

### ISSUE THREAD

**Issue by shadowdogg** [android/architecture-components-samples#658]
Hi,

Where does this get built in the code? Converting it to java but can't see where this is, been using prior code when it was java until this point where it only used FragmentManagers

**Comment by ianhanniballake** [comment]
Directions classes are built by [Safe Args](https://developer.android.com/guide/navigation/navigation-pass-data#Safe-args) from the navigation graph files.

**Comment by kyzgxiaoguo** [comment]
#692------------------ 原始邮件 ------------------
发件人: "Ian Lake"<notifications@github.com>
发送时间: 2020年1月27日(星期一) 上午7:57
收件人: "android/architecture-components-samples"<architecture-components-samples@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [android/architecture-components-samples] GithubBrowserSample -SearchFragmentDirections (#658)



Closed #658.
 
&mdash;
