### ISSUE TITLE
BoundaryCallback#onItemAtEndLoaded not firing with Placeholders for DB + Network

### ISSUE THREAD

**Issue by saturna** [android/architecture-components-samples#662]
onItemAtEndLoaded callback is decided as follows:
` final boolean dispatchEnd = mBoundaryCallbackEndDeferred
            && mHighestIndexAccessed >= size() - 1 - mConfig.prefetchDistance;`

with size() calculation to be as follows:
`mLeadingNullCount + mStorageCount + mTrailingNullCount`

When using a local Database for DataSource that acts as a cache, when "loadInitial" gets called, my database will have first page (20 items) present and will return those 20 items + the number of total items available from the network resource as:
`callback.onResult(events, 0, totalAvailableEvents); // events.size() = 20 totalAvailableEvents = 246`

When I scroll down the list, dispatchEnd (from first code snippet) gets decided; however, the calculation will always return false, since size() returns 246 (because it counts placeholders for not yet fetched network items).

As the result, only first page is ever loaded followed by placeholder cells that will never be replaced with data from the network since BoundaryCallback never invokes onItemAtEndLoaded().

Why does the size() take into account placeholder cells for deciding dispatchEnd? That doesn't make any sense.

**Comment by charlieaboumoussa** [comment]
Hello @saturna , how are you being able to display placeholders?

**Comment by saturna** [comment]
Hi @charlieaboumoussa , I use "getItemViewType(int position)" to return a placeholder cell if requested position references data page that has not been loaded yet (I maintain this information in my own model).

**Comment by charlieaboumoussa** [comment]
Hey @saturna , I am trying to determine the view type by checking whether the Object at position X is a view object or a null object, since I understood that the paging library returns null object to associate it with a placeholder.
Yet, no null items are present in the PagedList.

**Comment by dlam** [comment]
To display placeholders, you need to enable them in `PagedList.Config` (v2) or `PagingConfig` (v3), and then use a `DataSource` / `PagingSource` implementation that returns non-zero / counted values for placeholdersAfter/Before (this is how you provide the size of the data to Paging).

@charlieaboumoussa you are correct that `null` is the correct value for placeholders. I'd check the things I mentioned above to get it working!

**Comment by dlam** [comment]
As for this issue itself about triggering `BoundaryCallback`, if I'm being honest all development has moved onto the v3 APIs and the layered source case been completely reworked in v3 with `RemoteMediator` APIs, so I would recommend to migrate there.

I didn't look too deeply, but to guess at the original question about dataset size triggering remote boundary loads - the number of placeholders is supposed to reflect the count of your local dataset - if we triggered remote loads at the end of loaded data, and not just end of local data we would be fetching items from network you already have cached in DB. So there's some tradeoff here where it's not possible to know the desired intent... this is my best guess, but regardless I would recommend to migrate to the v3 APIs which separates placeholders counts (updateable per-page without tiling restrictions) from remote triggers, which are based on null-ness of key values in pages loaded by `PagingSource`.
