### ISSUE TITLE
[GithubBrowserSample] Lint errors/warnings and generally adhere to the Kotlin Style Guide

### ISSUE THREAD

**Issue by RodrigoMirandaMarenco** [android/architecture-components-samples#666]
Linter for the GithubBrowserSample project currently lists the following:

- Android: 1 warning
- General: 12 errors
- Groovy: 1 warning
- Kotlin: 8 warnings, 22 weak warnings
- XML: 4 errors, 3 warnings

Also, code should generally adhere to the Kotlin Style Guide:
https://developer.android.com/kotlin/style-guide

**Comment by RodrigoMirandaMarenco** [comment]
Also there are some broken Instrumentation tests, they can be fixed by removing said errors.

**Comment by ianhanniballake** [comment]
Most of these should be fixed already - we made a number of passes. Please feel free to submit pull requests for any remaining issues (preferably only one issue per pull request).
