### ISSUE TITLE
How can I  invoke loadAfter when net is reconnect

### ISSUE THREAD

**Issue by xiejinsorry** [android/architecture-components-samples#675]
It's a serious question.
I can auto invoke loadAfter method when the net is normal,
but after I loaded first page,I disconnect the net,
then I reconnect the internet ,I found that I can't invoke loadAfater method automactally,why?

**Comment by dlam** [comment]
In Paging2 you would have had to use something like [PagingRequestHelper](https://github.com/android/architecture-components-samples/commit/a2151cf66483560f76b041ba95ce96e931c50caf#diff-48465891ffa4ad774018ce9ca3b528e5L106), but a `.retry()` API is now directly available on `PagingDataAdapter` in Paging3.

**Comment by ghozimahdi** [comment]
Hello, I tried the `.retry ()` API, but it doesn't work. i am using rxPagingSource
