### ISSUE TITLE
NavigationAdvancedSample - home graph loses backstack

### ISSUE THREAD

**Issue by javaherisaber** [android/architecture-components-samples#677]
I'v integrated `NavigationExtensions` class to work with my bottomNavigation with 4 items
each one of these items have their own graph
when i navigate through them individually and then press back button to return to `home graph`
home backstack is gone and it doesn't display my `fixed start destination`
instead it display's last navigated fragment in `home graph`
surprisingly when i press back button here, it navigates out of app

**Comment by sobolvb** [comment]
@javaherisaber you fix it?

**Comment by javaherisaber** [comment]
@sobolvb 
seems like it was an internal issue in **Navigation** library itself
fixed in version 2.2.0

**Comment by Podox2** [comment]
Use app:defaultNavHost="false" for FragmentContainerView in xml
