### ISSUE TITLE
Animation on transition with nested graph

### ISSUE THREAD

**Issue by KevynBct** [android/architecture-components-samples#681]
Hello,

When I navigate to a nested graph it always run the exit animation "slide to right" even if I set another animation transition

**Comment by ianhanniballake** [comment]
This doesn't seem to be an issue with the samples. You can file an issue against Navigation on [the issue tracker](https://issuetracker.google.com/issues/new?component=409828) if you're still having an issue.

**Comment by glucadev** [comment]
Which of the samples has nested graphs? Not seeing use of it in the Basic or Advanced samples.

My issue is with included graphs. Animations to the start destination don't seem to trigger at all. I guess switch back to nested graphs?

**Comment by ianhanniballake** [comment]
You'd want to [file a bug against Navigation](https://issuetracker.google.com/issues/new?component=409828) with a project that reproduces your issue.

The issue tracker here is only for issues with the **samples themselves** and, like you said, there aren't any nested graphs in these samples.

**Comment by glucadev** [comment]
Ohhh, I get what you were saying now. I thought you were telling him that it was working correctly in the samples. Gotcha.

But included graphs should have working animations to the start destination? I'm just curious because it doesn't appear to be working. But moving back to nested graphs isn't that big of a deal.

**Comment by ianhanniballake** [comment]
An `<include>` just inflates the graph directly into the graph, the same as if it was nested directly. There's no runtime difference (in fact, post inflation, the `NavGraph` objects are identical and cannot be distinguished).

**Comment by glucadev** [comment]
Yeah, that's what I gathered from the docs, that it was essentially the same. I must be overlooking something.

**Comment by glucadev** [comment]
Ah yeah.. I was blocking the UI thread.. my mistake.
