### ISSUE TITLE
Databinding does not work with Kotlin coroutine ?

### ISSUE THREAD

**Issue by melvin11112017** [android/architecture-components-samples#683]
Here is my Kotlin Android code of a viewModel Function:
----------------------------------------------
```

editTextValueLiveData.setValue("456") 
 // OK.UI updates and EditText changes text to "456". Not use launch{} function

viewModelScope.launch {
    editTextValueLiveData.setValue("123")  
//NG.UI does not update and EditText has no change while using launch{} function 
//Though, editTextValueLiveData.value == "123" . 
}
```

----------------------------------------------
editTextValueLiveData binds with EditText 

Please help,thanks!

gradle-5.1.1
kotlinVersion = '1.3.41'
coroutinesVersion = "1.3.0-M2"

**Comment by ianhanniballake** [comment]
This doesn't seem to be an issue with the samples. You can file an issue against DataBinding on [the issue tracker](https://issuetracker.google.com/issues/new?component=192721) if you're still having an issue.
