### ISSUE TITLE
How do I try load-more when no more page in PageKeyedDataSource previously?

### ISSUE THREAD

**Issue by b95505017** [android/architecture-components-samples#685]
For example in the comments paging api, comments will grow with time. If I scroll to page 29 with key A and get only 1 comment currently, how do I try load-more manually about 1 minutes later from page 29 without reload from page 1?

**Comment by dlam** [comment]
This is unsupported in PageKeyedDataSource outside of initial key as Paging2 didn't provide a system to map an item's position to a page key. This functionality is now available in Paging3, which generalizes this behavior for all the DataSource types.
