### ISSUE TITLE
How can I create viewmodel per fragment inside viewpager

### ISSUE THREAD

**Issue by chethu** [android/architecture-components-samples#687]
Basically I want to create view model per fragment in view pager. each page in the view pager has different data to fetch from network. 

 View pager -> view pager adapter -> fragment with view model

Since all of these fragment using same view model, data in each page is replicating with same content. 

productsViewModel = ViewModelProviders.of(this, viewModelFactory)
            .get(categoryName!!, ProductsViewModel::class.java)

having category name doesn't work, because it still uses the same view model. 

Can you give us idea what could be the best for situation ??

**Comment by ianhanniballake** [comment]
This doesn't seem to be an issue with these samples. Consider posting a question on StackOverflow with your code and what you've tried.
