### ISSUE TITLE
Subclasses of ViewModel need to be public [android-arch-lifecycle]

### ISSUE THREAD

**Issue by kurthuwig** [android/architecture-components-samples#692]
Subclasses of `ViewModel` have to be `public` (and have `public` constructors) and not package-visible as otherwise they cannot be instantiated by this code

    ViewModelProviders.of(this).get(MyViewModel.class);

This code works in the IDE with instant run as it is silently changed to `public` but when you create an APK, they will stay package-visible and your code does not work.

I'd like to be able to use package-visible classes so that I can limit the scope of the view models to the only package where it is used.

**Comment by ianhanniballake** [comment]
This doesn't seem to be an issue with the samples. You can file an issue against Lifecycle on [the issue tracker](https://issuetracker.google.com/issues/new?component=413132) if you'd still like to see this changed.
