### ISSUE TITLE
Persistence Example Too Tightly Bound to LiveData

### ISSUE THREAD

**Issue by BenjaminHolland** [android/architecture-components-samples#694]
The Room Persistence example is extremely reliant on LiveData.

In particular, LiveData is used to solve a race condition that occurs between the initial query and the database being filled initially. The top results on google for instructions on how to fill the database when it's created all suffer from this race condition, and there doesn't appear to be official documentation on best practices concerning this use  case outside of this example. This makes it difficult to learn how to prevent this race condition using room on it's own or with any of the other result compatibility packages androidx provides for Room. 

Ideally an example would be provided using only Room, or better documentation of this functionality would be provided. Using only room would better illustrate of the issue and it solution.

**Comment by ianhanniballake** [comment]
Room has added support for [prepopulating the database](https://developer.android.com/training/data-storage/room/prepopulate), which does not suffer from these types of issues, whether you use `LiveData` or not.
