### ISSUE TITLE
Add Kotlin extension method alternative to LiveDataTestUtil

### ISSUE THREAD

**Issue by tomaszrykala** [android/architecture-components-samples#697]
Wouldn't there be a good argument to replace the Java-like static utility class approach of [LiveDataTestUtil](https://github.com/googlesamples/android-architecture-components/blob/master/BasicSample/app/src/androidTest/java/com/example/android/persistence/LiveDataTestUtil.java) with a Kotlin extension method on LiveData itself? Alternatively to provide the option along-side it?
```
/**
 * Get the value from a LiveData object. We're waiting for LiveData to emit, for 2 seconds.
 * Once we got a notification via onChanged, we stop observing.
 */
fun <T> LiveData<T>.getData(): T {
    val data = arrayOfNulls<Any>(1)
    val latch = CountDownLatch(1)
    val observer = object : Observer<T> {
        override fun onChanged(o: T?) {
            data[0] = o
            latch.countDown()
            removeObserver(this)
        }
    }
    observeForever(observer)
    latch.await(2, TimeUnit.SECONDS)

    @Suppress("UNCHECKED_CAST")
    return data[0] as T
}
```

**Comment by ianhanniballake** [comment]
The `BasicSample` is in Java (and that includes its tests). We've updated the GithubBrowserSample's version to match the LiveDataSample so that they both use an extension method on LiveData.
