### ISSUE TITLE
GithubBrowserSample : Update ViewModel injection example to the new SavedStateViewModelFactory

### ISSUE THREAD

**Issue by NitroG42** [android/architecture-components-samples#700]
The GithubBrowserSample is a good sample for developpers who wants to make an app using Dagger 2.
The last lifecycle alpha release (2.2.0-alpha03) seems to push the usage of saving state in the viewmodel. The issue is that the sample was not updated to reflect this usage, as the [GithubViewModelFactory](https://github.com/googlesamples/android-architecture-components/blob/master/GithubBrowserSample/app/src/main/java/com/android/example/github/viewmodel/GithubViewModelFactory.kt) is still a standard factory with no saved state.

I'm pretty sure the solution is explained here https://proandroiddev.com/saving-ui-state-with-viewmodel-savedstate-and-dagger-f77bcaeb8b08 and use Assisted Inject.
I also wonder if there is another way so I'll look for updates !

**Comment by ianhanniballake** [comment]
The one case where the GithubBrowserSample needed saved state was addressed in 12e6ee4c2198bdc6c39c51d10670dc86c49470f1 - all you need to do is extend `AbstractSavedStateViewModelFactory`

**Comment by NitroG42** [comment]
At the time of the issue this sample was using Dagger 2 as a way to inject viewmodels. It seems it has changed for a service locator pattern which is probably the right to fix the issue for this small  sample. Though I still wonder if there is a simple way to combine saved instance viewmodel factory with dagger 2.
