### ISSUE TITLE
Notifcation Issue : when app is Background and Closing State using Navigation Component

### ISSUE THREAD

**Issue by rspapneja** [android/architecture-components-samples#701]
Hello Sir
 
**My Problem. :The following code is not  working  (Close/Background state ) . But  this code work only when app is open state

**App open State:**

 redirect the .setDestination(R.id.profileFragment)    **/ / working fine**

  **closing State or Background state**   

not redirect the  .setDestination(R.id.profileFragment) ... when app is background/ Closing state. But redirect the parent start destination of  navigation graph

   var args = Bundle()
        args.putString("arg", "hello")

            val deeplink =  NavDeepLinkBuilder(this)
                //.setComponentName(StoreActivity::class.java)
                .setGraph(R.navigation.navigation_graph)
                .setDestination(R.id.profileFragment)
                .setArguments(
                        args
                )
                .createPendingIntent()

        val notificationManager = getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            notificationManager.createNotificationChannel(NotificationChannel(
                    ""+11, "Deep Links", NotificationManager.IMPORTANCE_HIGH))
        }
        val builder = NotificationCompat.Builder(
                this,""+11)
                .setContentTitle("Navigation")
                .setContentText("Deep link to Android")
                .setSmallIcon(R.drawable.ic_arrow)
                .setContentIntent(deeplink)
                .setAutoCancel(true)
        //notificationManager.notify(0, builder.build())
        notificationManager.notify(0,builder.build())

**Comment by ianhanniballake** [comment]
This doesn't seem to be an issue with the samples. You can file an issue against Navigation on [the issue tracker](https://issuetracker.google.com/issues/new?component=409828) if you're still having an issue.
