### ISSUE TITLE
What will be the best way of adding a new product to the list of products in BasicSample?

### ISSUE THREAD

**Issue by damms005** [android/architecture-components-samples#704]
In my attempt to understand how the android arch components work, I read the docs and studied the `BasicSample` code. However, I am unable to figure out the best way to add new `Products` and/or add `Comments` to existing products (e.g. launch new intent activity with TextViews to add/edit/delete). 

I wish an explanation to this be made: as basic and fundamental as can be. The only thing I can conclude on from my knowledge about this so far is that the `ProductAdapter` such be aware of such data addition/deletion. Hence I think it should be implemented in that adapter. I also think another way of achieving this will be to add required add/edit methods to `DataRepository.java`. It also seems possible to do a binding-in-xml thing; or it should be implemented in the ProductsListFragment.java, or via the ProductAdapter?

**Comment by ianhanniballake** [comment]
The Room database is the source of truth, so yes, your Repository and its underlying database should be where you make changes. Those will be automatically reflected in the UI.
