### ISSUE TITLE
Flowable/Observable callback not triggered when there is no data in room db.

### ISSUE THREAD

**Issue by RaaviKumar** [android/architecture-components-samples#718]
When there is no data in database the result is not received using **Flowable/Observable** Room RxJava.

Consider following example:

@Transaction
@Query("SELECT * FROM products " WHERE brandId = :productId")
**fun getProductByBrand(productId : Int): Observable<Product>**

Result:
**If no match found in the table, Observable onNext() is not getting triggered.**

To get the result, **return **Observable<List<Product'>>** instead of 
**Observable<Product'>**. so if no data found in db Observable **onNext() will emit list with 0 count and same in case of mapper**.

**Expected Result:
Observable/Flowable should emit data if no match found in db**

**Comment by haihack** [comment]
I have encountered the same issue. Any solution?

**Comment by ianhanniballake** [comment]
This doesn't seem to be an issue with the samples. Please file an issue against Room on [the issue tracker](https://issuetracker.google.com/issues/new?component=413107) if this is still an issue.
