### ISSUE TITLE
Navigation component navigates back shows blank fragment 

### ISSUE THREAD

**Issue by DanteAndroid** [android/architecture-components-samples#720]
I have a tablayout+fragments, when I click the item in the fragment, it navigates to detail fragment which works fine. but then I click back, it shows empty. When I swipe to other tab, then swipe back, its content then appears.
![Screenshot_1568339485](https://user-images.githubusercontent.com/10005563/64832389-60977100-d60c-11e9-86f3-df0280d95981.png)

**Comment by krongnang** [comment]
I have a same issues

**Comment by DanteAndroid** [comment]
@krongnang I've quit trying the navigation. It's not so great to use even in personal project IMO.

**Comment by ianhanniballake** [comment]
This doesn't seem to be an issue with the samples. You can file an issue against Navigation on [the issue tracker](https://issuetracker.google.com/issues/new?component=409828) if you're still having an issue.

(It sounds like you're not passing the `childFragmentManager` to your `ViewPager` adapter).
