### ISSUE TITLE
PagedListAdapter display admob native advanced ad

### ISSUE THREAD

**Issue by efratos1** [android/architecture-components-samples#722]
Hey everyone I was wondering if any one knows the best way to implement admob native advanced after 7 rows in PagedListAdapter class.  Using normal recyclerview adapter class is easy to implement admob. Thank you

**Comment by gdianov** [comment]
> Hey everyone I was wondering if any one knows the best way to implement admob native advanced after 7 rows in PagedListAdapter class. Using normal recyclerview adapter class is easy to implement admob. Thank you

Did you manage to do this?

**Comment by ianhanniballake** [comment]
In the future, this is going to be handled by implementing a `MergeAdapter` as explained on [the issue](https://issuetracker.google.com/issues/147833132).

Please make sure you're filing issues against Paging in the [Paging issue tracker](https://issuetracker.google.com/issues/new?component=413106) as the issues here are solely for the sample code here.
