### ISSUE TITLE
Application crashes after turn off permission from settings

### ISSUE THREAD

**Issue by YervandAleksanyan** [android/architecture-components-samples#725]
Hi, I have an issue with the navigation component.

My application has 4 states and for each state I have navigation graph when user launch application my starter activity launching one of the navigation graphs depending on the app state.
 
Bug causing scenario

When the application starts with the "graph_A" and the user hides the application and goes to the application settings section on the phone and disables the camera permission, and then reopen the app and when  starter  activity of app tries to start the navigation graph, for example, "graph_B", the application crashes with this exception

`java.lang.IllegalStateException: unknown destination during restore: graph_a `

Navigation library version  -  '2.1.0-alpha02'

**Comment by AliAzaz** [comment]
Have u applied any solution for it? and in which project: NavigationAdvancedSample or NavigationBasicSample

**Comment by ianhanniballake** [comment]
This doesn't seem to be an issue with the samples. You can file an issue against Navigation on [the issue tracker](https://issuetracker.google.com/issues/new?component=409828) if you're still having an issue.
