### ISSUE TITLE
LiveDataSample Unit Test - Observe Multiple Values

### ISSUE THREAD

**Issue by AdamSHurwitz** [android/architecture-components-samples#727]
# Expected

Use `observeForTesting` helper method in [LiveDataTestUtil.kt](https://github.com/googlesamples/android-architecture-components/blob/master/LiveDataSample/app/src/test/java/com/android/example/livedatabuilder/util/LiveDataTestUtil.kt#L61) in order to observe multiple values of a LiveData object emitted consecutively in a local unit test as featured in @JoseAlcerreca's [Medium post](https://medium.com/androiddevelopers/unit-testing-livedata-and-other-common-observability-problems-bb477262eb04) and Google's [LiveDataSample](https://github.com/googlesamples/android-architecture-components/tree/master/LiveDataSample) in [LiveDataViewModelTest.kt](https://github.com/googlesamples/android-architecture-components/blob/master/LiveDataSample/app/src/test/java/com/android/example/livedatabuilder/LiveDataViewModelTest.kt#L78).

For the code below, when ran in non-testing/production, the app logs the ContentViewModel emitting the `SwipeToRefresh` and `SnackBar` `viewEffect` LiveData events in that order, as expected. 

## Code

The ContentViewModel.kt changes the value of `viewEffect` LiveData twice in the error case below saving two `Event` objects one right after another. 

1. `SwipeToRefresh`
2. `SnackBar`

The ContentViewModelTest.kt checks that both values `SwipeToRefresh` and
`SnackBar` are emitted.

_ContentViewModelTest.kt_

    private fun assertContentListError(...) {
        if (test.lceState == ERROR)
            when (test.feedType) {
                MAIN -> {
                    contentViewModel.viewEffect.observeForTesting {
                        if (event is SwipeToRefresh)
                            contentViewModel.viewEffect.value!!.peekEvent().also { effect ->
                               assertThat(effect.javaClass).isEqualTo(ContentViewEffect.SwipeToRefresh::class.java)
                            }
                        contentViewModel.viewEffect.value!!.peekEvent().also { effect ->
                            assertThat(effect.javaClass).isEqualTo(SnackBar::class.java)
                            if (effect is SnackBar) 
                                assertThat(effect).isEqualTo(SnackBar(...))
                        }
                    }
                }
                ...
    }

_ContentViewModel.kt_

     private fun getContentList(...) =
            if (feedType == MAIN)
                switchMap(getMainFeedList(...)) { lce ->
                    when (lce) {
                        ...
                        is Error -> {
                            if (event is ContentViewEvent.SwipeToRefresh)
                                _viewEffect.value = Event(SwipeToRefresh(false))
                            _viewEffect.value = Event(SnackBar(...))
                            switchMap(queryMainContentList(timeframe)) { pagedList ->
                                MutableLiveData<PagedList<Content>>().apply { this.value = pagedList }
                            }
                        }
                    }
                }
                ...

# Observed

**This appears to be an issue with multiple LiveData values being emitted in the local unit test consecutively.**

`SwipeToRefresh` and `SnackBar` are expected to be emitted by the `viewEffect` LiveData in sequential order one after another in the test. Instead there is an error message with a different value `ScreenEmpty` being read which means the LiveData is not being emitted properly in the unit test as it works as expected in production. 

## Sample Output

    org.opentest4j.AssertionFailedError: 
    Expecting: <app.coinverse.content.models.ContentViewEffect.ScreenEmpty>
    to be equal to:
    <app.coinverse.content.models.ContentViewEffect.SnackBar>
    but was not.
    Expected :class app.coinverse.content.models.ContentViewEffect$SnackBar
    Actual   :class app.coinverse.content.models.ContentViewEffect$ScreenEmpty

# Attempted Solutions

_ContentViewModelTest.kt_

**1. `getOrAwaitValue`**

    if (event is SwipeToRefresh)
        contentViewModel.viewEffect.getOrAwaitValue().peekEvent().also { effect ->
            assertThat(effect.javaClass).isEqualTo(ContentViewEffect.SwipeToRefresh::class.java)
        }
    contentViewModel.viewEffect.getOrAwaitValue().peekEvent().also { effect ->
        assertThat(effect.javaClass).isEqualTo(SnackBar::class.java)
        if (effect is SnackBar) 
            assertThat(effect).isEqualTo(SnackBar(...))
    }

**2. `observeForever`**

    contentViewModel.viewEffect.observeForever {
        if (event is SwipeToRefresh)
            it.peekEvent().also { effect ->
                assertThat(effect.javaClass).isEqualTo(ContentViewEffect.SwipeToRefresh::class.java)
            }
        it.peekEvent().also { effect ->
            assertThat(effect.javaClass).isEqualTo(SnackBar::class.java)
            if (effect is SnackBar) 
                assertThat(effect).isEqualTo(SnackBar(...))
        }
    }

**Comment by JoseAlcerreca** [comment]
LiveData is a data holder, not a mechanism for handling streams of values. You sholdn't use it to emit values consecutively, especially if you're exposing state in an Event<>.

Just expose two `LiveData<Event<T>>`. One for snackbar and one for the swipeToRefresh (result?).

**Comment by AdamSHurwitz** [comment]
Thanks for the feedback @JoseAlcerreca !

> Just expose two LiveData<Event<T>>.

I believe that's what's implemented below. **Are you suggesting to have two separate LiveData objects, and not use the `viewEffect` pattern below?**  

**`viewEffect` pattern** - Part of the [Unidirectional Data Flow](https://medium.com/hackernoon/android-unidirectional-flow-with-livedata-bf24119e747) pattern in order to pass non-persistent UI events from the ViewModel to the view in a LiveData object storing different types of events defined by a [Sealed class](https://kotlinlang.org/docs/reference/sealed-classes.html#sealed-classes).

The events are emitted as expected in non-test runtime code. This appears to be a localized issue within the unit test.

_ContentViewModel.kt_

    class ContentViewModel : ViewModel() {
        val viewEffect: LiveData<Event<ContentViewEffect>> get() = _viewEffect
        private val _viewEffect = MutableLiveData<Event<ContentViewEffect>>()
        ...
    }

_ContentViewEffect.kt_

    sealed class ContentViewEffect {
        data class SwipeToRefresh(val isEnabled: Boolean) : ContentViewEffect()
        data class SnackBar(val text: String) : ContentViewEffect()
    }

_ContentFragment.kt_

    private fun observeViewEffects() {
        contentViewModel.viewEffect.observe(viewLifecycleOwner, EventObserver { effect ->
            when (effect) {
                is SwipeToRefresh -> /* Something happens here. */
                is SnackBar -> /* Something happens here. */
                ...

**Comment by JoseAlcerreca** [comment]
If you're going to expose state, you can't use a _slot_ that can be potentially used by two different messengers at the same time.

If you want to expose just one state object, model it to have two events inside.

> The events are emitted as expected in sequential order in non-test runtime code. This appears to be an isolated issue within the unit test.

I think you're relying on an implementation detail. Even if it was guaranteed and documented that every call to setValue() is emitted to all observers before accepting a new value, if that code is ever changed to a postValue() or the observers are in a transient state, it could end up creating an evasive bug. I think you should model your state differently or use a construct that guarantees what you're trying to do.

**Comment by AdamSHurwitz** [comment]
I refactored the `ContentViewEffect` state object to have LiveData<Event> attributes for each specific UI effect passed to the view instead of passing one LiveData<Event> and using a generic Sealed class. This avoids "_having a **slot** used by two different messengers at the same time_".

I will post a basic updated example later today. 

I need to fix the code as I replaced LiveData creation in the ViewModel using `MutableLiveData().apply { it.value = 'someValue' }` pattern with `liveData { emit('someValue') }`  coroutines. The coroutines are breaking the tests so I'll refactor back to `MutableLiveData` to demonstrate the LiveData state pattern.

**Comment by AdamSHurwitz** [comment]
@JoseAlcerreca, I refactored the _ContentViewEffect_ state  in order to ensure there is not one _slot_ that can be potentially used by two different messengers. The state contains `LiveData<Event>` attributes for each temporary UI effect passed to the view.

This strategy has helped better organize the unit tests. However, there is still one particular LiveData value attribute, `swipeToRefresh` in the `Error` state that is being emitted as expected in the runtime error state, but not in the unit tests. Therefore, I know the LiveData is being saved accordingly.

_ContentViewEffect.kt_

    data class ContentViewEffects(
        val swipeToRefresh: LiveData<Event<SwipeToRefreshEffect>> = MutableLiveData(),
        val snackBar: LiveData<Event<SnackBarEffect>> = MutableLiveData())

_ContentViewModel.kt_

    private fun getContentList(...) =
            if (feedType == MAIN)
                switchMap(getMainFeedList(...)) { lce ->
                    when (lce) {
                        ...
                        is Error -> {
                            _viewEffect.value = ContentViewEffects(swipeToRefresh = liveData {
                                emit(Event(SwipeToRefreshEffect(false)))
                            })
                            _viewEffect.value = ContentViewEffects(snackBar = liveData {
                                emit(Event(SnackBarEffect(...)))
                            })
                            switchMap(queryMainContentList(timeframe)) { pagedList ->
                                liveData { emit(pagedList) }
                            }
                    }
                }
                ...

_ContentFragment.kt_

    private fun observeViewEffects() {
        contentViewModel.viewEffect.observe(viewLifecycleOwner, Observer { effect ->
            effect.swipeToRefresh.observe(viewLifecycleOwner, EventObserver {
                // Something happens here.
            })
            effect.snackBar.observe(viewLifecycleOwner, EventObserver {
                // Something happens here.
            })
        })
        ...
    }

_ContentViewModelTest.kt_

    when (test.lceState) {
        LOADING -> contentViewModel.viewEffect.getOrAwaitValue().swipeToRefresh.getOrAwaitValue().peekEvent().also { effect -> 
            assertThat(effect).isEqualTo(SwipeToRefreshEffect(true))
        }
        CONTENT -> contentViewModel.viewEffect.getOrAwaitValue().swipeToRefresh.getOrAwaitValue().peekEvent().also { effect -> 
            assertThat(effect).isEqualTo(SwipeToRefreshEffect(false))
        }
        ERROR -> contentViewModel.viewEffect.getOrAwaitValue().swipeToRefresh.getOrAwaitValue().peekEvent().also { effect ->
            assertThat(effect).isEqualTo(SwipeToRefreshEffect(false))
        }
    }

# Attempted Solution

Using the the `observeForTesting` [util function](https://github.com/googlesamples/android-architecture-components/blob/master/LiveDataSample/app/src/test/java/com/android/example/livedatabuilder/util/LiveDataTestUtil.kt#L61), shown in the Android Architecture Components [LiveDataSample](https://github.com/googlesamples/android-architecture-components/blob/master/LiveDataSample/app/src/test/java/com/android/example/livedatabuilder/LiveDataViewModelTest.kt#L78) in order to observe the LiveData until it is done executing. 

_ContentViewModelTest.kt_

    if (test.feedType == MAIN && event is SwipeToRefresh)
    contentViewModel.viewEffect.observeForTesting {
        when (test.lceState) {
            LOADING ->
                contentViewModel.viewEffect.value?.swipeToRefresh?.value.also { effect ->
                    assertThat(effect).isEqualTo(SwipeToRefreshEffect(true))
                }
            CONTENT ->
                contentViewModel.viewEffect.value?.swipeToRefresh?.value.also { effect ->
                    assertThat(effect).isEqualTo(SwipeToRefreshEffect(false))
                }
            // FIXME
            // Try observeForTesting util. function.
            ERROR ->
                contentViewModel.viewEffect.value?.swipeToRefresh?.value.also { effect ->
                    assertThat(effect).isEqualTo(SwipeToRefreshEffect(false))
                }
        }
    }

**Comment by AdamSHurwitz** [comment]
I resolved the issue with the null LiveData state attribute `swipeToRefresh`. 🎉The problem was that every time a view effect event was saved to the LiveData state object _ContentViewEffect_, the object was being recreated with default values. Multiple events happening in close succession appeared to be clearing out the attribute before it was observed by the unit test.

# Solution

Use Kotlin's [copy](https://kotlinlang.org/docs/reference/data-classes.html#copying) function to copy an object altering the attribute for the given view effect while keeping the other values unaltered.

_ContentViewModel.kt_

    val viewEffect: LiveData<ContentViewEffect> get() = _viewEffect
    private val _viewEffect = MutableLiveData<ContentViewEffect>()

    private fun getContentList(...) =
            if (feedType == MAIN)
                switchMap(getMainFeedList(...)) { lce ->
                    when (lce) {
                        ...
                        is Error -> {
                            _viewEffect.value = _viewEffect.value?.copy(swipeToRefresh = liveData {
                                emit(Event(SwipeToRefreshEffect(false)))
                            })
                            _viewEffect.value = _viewEffect.value?.copy(snackBar = liveData {
                                emit(Event(SnackBarEffect(...)))
                            })
                            switchMap(queryMainContentList(timeframe)) { pagedList ->
                                liveData { emit(pagedList) }
                            }
                        }
                    }
                }
                ...

_ContentViewModelTest.kt_

The test does not need to changed.

    when (test.lceState) {
        LOADING -> contentViewModel.viewEffect.getOrAwaitValue().swipeToRefresh.getOrAwaitValue().peekEvent().also { effect -> 
            assertThat(effect).isEqualTo(SwipeToRefreshEffect(true))
        }
        CONTENT -> contentViewModel.viewEffect.getOrAwaitValue().swipeToRefresh.getOrAwaitValue().peekEvent().also { effect -> 
            assertThat(effect).isEqualTo(SwipeToRefreshEffect(false))
        }
        ERROR -> contentViewModel.viewEffect.getOrAwaitValue().swipeToRefresh.getOrAwaitValue().peekEvent().also { effect ->
            assertThat(effect).isEqualTo(SwipeToRefreshEffect(false))
        }
    }
