### ISSUE TITLE
NavigationAdvancedSample - same activity no bottomNavigationBar

### ISSUE THREAD

**Issue by jQrgen** [android/architecture-components-samples#730]
Hello 

It would be awesome with an example in NavigationAdvancedSample displaying best practices for implementing navigation graphs outside of the BottomNavigationView and navigating back and forth

Currently investigating NavigationExtensions.kt in the NavigationAdvancedSample, but it all seems a bit unclean.

Anyone got some pointers?

Thanks

**Comment by akamahesh-db** [comment]
So Is there any solution?
@ianhanniballake 
@jQrgen Did you find any way to deal with it ?

**Comment by adilove** [comment]
We are still waiting ^^

**Comment by jQrgen** [comment]
Use an enum in the Activity to hide/show it using fragments lifecycles

**Comment by jQrgen** [comment]
*** Trigger height of bottom nav to 0 and back

#AndroidLife

**Comment by ianhanniballake** [comment]
The `setupWithNavController` gives you a controller back that you can observe to get the current `NavController` - that's what we use to do `setupActionBarWithNavController()`. That's also precisely where you'd [listen for navigation events](https://developer.android.com/guide/navigation/navigation-ui#listen_for_navigation_events) to hide/show global UI such as a bottom bar, just like if you had a single NavController.

Just make sure to keep track of the previous navController and call `removeOnDestinationChangedListener()` to unregister your previously set listener:

```
val listener = NavController.OnDestinationChangedListener { _, destination, _ ->
   if(destination.id == R.id.full_screen_destination) {
       bottomNavigationView.visibility = View.GONE
   } else {
       bottomNavigationView.visibility = View.VISIBLE
   }
}
var currentController: NavController? = null
controller.observe(this, Observer { navController ->
    setupActionBarWithNavController(navController)
    // Unregister the old one if it exists
    currentController?.removeOnDestinationChangedListener(listener)
    // Add the listener to the new NavController
    navController.addOnDestinationChangedListener(listener)
    currentController = navController
})
```

**Comment by jQrgen** [comment]
Ohh nice! Are those new docs?? :))

**Comment by jQrgen** [comment]
@ianhanniballake
Thanks for the code snippet.

What if the destinations are in separate modules that run in the same Activity?

Give that the recommendation from google is one Activity for the whole app, we should be able to handle a bottom navigation bar that is decoupled from other modules in some way.

**Comment by ianhanniballake** [comment]
That particular code example in the docs has been up since [April 14, 2019](https://web.archive.org/web/20190414153815/https://developer.android.com/guide/navigation/navigation-ui).

You might look at an [argument based listener](https://stackoverflow.com/a/57928305/1676363) if you want something not tied to destination IDs.
