### ISSUE TITLE
Passing context from fragment to view model using view model factory

### ISSUE THREAD

**Issue by Haider8** [android/architecture-components-samples#740]
For saving a string in `SharedPreferences` through fragment's view model I passed the `context` into view model by creating `viewModelFactory` . I initialized the view model by passing the context from the fragment using the constructor.

I want to ask if this is the right approach or is there some better way to do this?

**Comment by Zhuinden** [comment]
Why aren't you passing `SharedPreferences` directly if you're already using `viewModelFactory`?

**Comment by Haider8** [comment]
Thanks for the reply. Yes, ultimately I passed shared preference with context in its constructor.

**Comment by ianhanniballake** [comment]
If you're using `AndroidViewModel`, you'll get an `Application` object (i.e., the application context) by default. If you're providing your own constructor, yes, it would be appropriate to pass in a `SharedPreferences` or other object you need to the constructor of your `ViewModel`.
