### ISSUE TITLE
Android Navigation Architecture Component - setTargetFragment for DialogFragment

### ISSUE THREAD

**Issue by minhbnt-1512** [android/architecture-components-samples#750]
I want to setTargetFragment before navigating to the DialogFragment. In my dialog fragment, I call the API. If the API returns data successfully then dialog fragment is dismissed and parent fragment update UI. How can I do this when using Navigation Architecture Component

**Comment by fatihergin** [comment]
- You can achieve this with shared view model if you use view model. 
- Navigation Architecture Component oriented solution is creating a new action that takes an argument and implements popUpTo (to parent fragment) attribute.
- Passing callback to dialog fragment may help you as an alternative.

**Comment by 0rp3u** [comment]
Passing callback is a bad solution, it won't work if you face process death or in any case where callback is serialized, since the callback keeps and instance to the fragment that created it and fragments are not serializable, I personally use a shared viewModel. There is a issue open for this, and Google's it's working on this.

**Comment by ianhanniballake** [comment]
Note that this issue tracker is for issues with these samples, not general issues or questions about the individual libraries (for example, Navigation bugs/feature requests should be filed against the [Navigation issue tracker](https://issuetracker.google.com/issues/new?component=409828)).

If you had done that, you would have been pointed to [the existing issue around navigating for a result](https://issuetracker.google.com/issues/79672220), which has just been fixed and released as part of [Navigation 2.3.0-alpha02](https://developer.android.com/jetpack/androidx/releases/navigation#2.3.0-alpha02).

You can read more about how to return a result in Navigation by reading the [new documentation](https://developer.android.com/guide/navigation/navigation-programmatic#returning_a_result). There's even a section specifically about dialog destinations.

**Comment by parisbs** [comment]
@ianhanniballake the link of the new documentation don't have the Dialog cases information yet, can you share another link where we can find code examples please?

**Comment by ianhanniballake** [comment]
@parisbs - all of the dialog differences are [specifically mentioned on that page](https://developer.android.com/guide/navigation/navigation-programmatic#additional_considerations).
