### ISSUE TITLE
GithubBrowserSample unit test coverage report

### ISSUE THREAD

**Issue by gongzelong0718** [android/architecture-components-samples#752]
I guess I need to execute 

`./gradlew fullCoverageReport`

I saw the JaCoCo plugin. How to get the report of unit test coverage?

**Comment by gongzelong0718** [comment]
Sadly, I do not find the report as below

<img width="1458" alt="Screen Shot 2019-11-11 at 12 28 03 PM" src="https://user-images.githubusercontent.com/6286811/68560999-c3777e00-047e-11ea-9a27-affb94686ed0.png">

Did I do wrongly?

```
12:26:26 V/ddms: execute: returning

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.6.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 49s
64 actionable tasks: 2 executed, 62 up-to-date
```

And I also wonder, I only need to get the local unit test. Why do I have to run the androidTest suite?

**Comment by gongzelong0718** [comment]
@dlam I do not know how to reopen the issue, could you help me?

**Comment by dlam** [comment]
Sorry I may have gotten the path wrong - have you checked under the reports folder? The .ec file is used to generate the html report so it should be there if you're able to generate a .ec file with jacoco.

**Comment by dlam** [comment]
The gradle logs should also give you the path if you run with --info

**Comment by gongzelong0718** [comment]
Hi, Dustin

from the screenshot, I can see the .ec file, but I guess the report should be .html file, or am I wrong.

BTW, have you seen the Jacoco Overall Coverage Summary, it will show the overall and every folder or package 's coverage, could you give me a sample report using your way?

**Comment by gongzelong0718** [comment]
I also wonder what the full coverage report location and where to set it:

From the result:
$buildDir/reports/jacoco/fullCoverageReport/html
<img width="524" alt="Screen Shot 2019-11-12 at 6 06 05 PM" src="https://user-images.githubusercontent.com/6286811/68662139-35cb8980-0577-11ea-8f7a-6a6ca1fc3292.png">


$buildDir/reports/coverage/debug/index.html
<img width="1226" alt="Screen Shot 2019-11-12 at 6 06 11 PM" src="https://user-images.githubusercontent.com/6286811/68662155-39f7a700-0577-11ea-9872-00150e7a7e5d.png">


https://docs.gradle.org/current/userguide/jacoco_plugin.html


Property | Gradle default
reportsDir | $buildDir/reports/jacoco

But it shows nothing, why the report with content is located in $buildDir/reports/coverage/debug/index.html?
