### ISSUE TITLE
How to use one LiveData for multiple data/state and survive from os kill/restore the activity

### ISSUE THREAD

**Issue by lannyf77** [android/architecture-components-samples#753]
Having two liveData one for the true data, one for the state i.e.  states such as complete, or failure with some code.

```
data_liveData?.observe(viewLifecycleOwner,
                Observer<List<Data>> { list ->
                    list?.let {
                        ...
                    }
                })

state_liveData?.observe(viewLifecycleOwner,
                Observer<State> { state ->
                    state?.let {
                        ...
                    }
                })
```

now want to change to use only one liveData for delivering both data and state.

we could define a wrapper class 
```
class Wrapper (val data: List<Data>:?=null, val state: State?=null)

```
and 

``` 
wrapper_liveData?.observe(viewLifecycleOwner,
                Observer<Wrapper> { wrapper ->
                    if (wrapper.data != null) {
                       // handle data post
                    } else if (wrapper.state != null) {
                       // handle state
                    }
                })
```

it works, but there is an issue and not sure what is the recommended way to deal with it.

when registering to observe the liveData, if there has been some previously posted data it will be immediately delivered to the observer's onChange().

What if there has been some data list posted before an error state post to the liveData, and then os kills the activity and then restores it back.

During the restoring flow the liveData (still alive and survived from the os killing the fragment in the viewModel) is re-observed by the fragment's start up code, which immediately receives the last posted value in the liveData, and which is the `State`.  

But the problem is the fragment UI will not be able restore with the previously displayed data on the UI.

someone says in restoring case just do as a fresh start (such re-pulling data from the remote repository. But isnt that is what the viewModel is trying to help to avoid?)

seems `MediatorLiveData` are mentioned in a few posts for combining multiple liveData.  But how does it help in the case of os killing/re-storing flow if the last post is from the state channel?

**Comment by ianhanniballake** [comment]
ViewModels and LiveData do not survive process death, they only survive configuration changes. You should make sure you're saving instance state to survive process death (see the recently added [ViewModel SavedState integration](https://developer.android.com/topic/libraries/architecture/viewmodel-savedstate) for one approach to this).
