### ISSUE TITLE
Here is a bug in projecct of BasicSample, when query in database。

### ISSUE THREAD

**Issue by WalKingMan007** [android/architecture-components-samples#759]
Bug：
     when I every click the button with the id of products_search_btn to qury product, the app's memory will increase。 
      when click search button, I will got anew Object  RoomTrackingLiveData by the method of searchProducts. Next the object of RoomTrackingLiveData will invoke observe，it will create a new Objext of Observer, and it will be hold by LifecycleRegistry.
      So, I think it's maybe not a good idea to query database. I hope it will be solved, avoid coder following suit. 
                                                                                                                                          Thank！！！

**Comment by ianhanniballake** [comment]
Good catch. We shouldn't be starting a new `observe` every time the `products_search_btn` is pressed. Instead, we should just be changing the current query we're observing by using a [transformation](https://developer.android.com/topic/libraries/architecture/livedata#transform_livedata)
