### ISSUE TITLE
Is it necessary to use fragment in the activity?

### ISSUE THREAD

**Issue by evansherry** [android/architecture-components-samples#761]
Recently learning[ android-architecture-samples](https://github.com/android/architecture-samples/tree/todo-mvvm-databinding/todoapp), I found that each activity uses fragment, even if the activity doesn't really need fragments, in my opinion, this makes the activity lazy and leads to a lot of files.

For example, [TaskDetailActivity](https://github.com/android/architecture-samples/blob/712c14538a0ab208b4db79970b0996f26f2ba5fe/todoapp/app/src/main/java/com/example/android/architecture/blueprints/todoapp/taskdetail/TaskDetailActivity.java) sets the Toolbar, and other view work is given to the [TaskDetailFragment](https://github.com/android/architecture-samples/blob/712c14538a0ab208b4db79970b0996f26f2ba5fe/todoapp/app/src/main/java/com/example/android/architecture/blueprints/todoapp/tasks/TasksFragment.java).why use a fragment instead of the activity to achieve, you will find that the entire demo is doing this, I don't think this is a meaningless question. There must be reason to do so.

Can anyone tell me why I wrote this, what are the benefits? Thank you!

**Comment by ianhanniballake** [comment]
Feel free to file an issue against the `architecture-samples` project for stylistic choices in their repository.
