### ISSUE TITLE
How can i have a fragment without bottom navigation.

### ISSUE THREAD

**Issue by aukhuongduy** [android/architecture-components-samples#763]
How can i have a fragment without bottom navigation?

## Question about Navigation Components? 
I trying to create a application like NavigationAdvancedSample with Bottom Navigation Bar. But i don't know how can i create a fragment without BottomNavigation ? 
For very common case AuthenticationActivity-> MainAcvitity(include BottomNavigation). 
I tried move bottomNav into a fragment named "MainFragment" but there are no supportNavigationUp() in fragment. 
I also tried start MainActivity from other nav_graph but no option like "Intent.FLAG_ACTIVITY_NO_HISTORY".

Thank you!
#564  
##NavigationAdvancedSample

**Comment by nguyenvanminhfptpoly** [comment]
addFinish()

**Comment by akamahesh-db** [comment]
@nguyenvanminhfptpoly can you elobarate more on this?
@aukhuongduy have you found any solution to this

**Comment by ianhanniballake** [comment]
Dup of #730
