### ISSUE TITLE
How to clear all fragments in current tab and back to root fragment in first tab

### ISSUE THREAD

**Issue by ngocmanh1609** [android/architecture-components-samples#767]
Hi all,
I am creating an example Android using Navigation component with custom tabs. Each tab have its own NavHost and nav graph. Now I want to click a button in any tab, the expected result is the current tab is clear to root, and it will back to first tab. How can I navigate it easily, please help? Thank you so much.

**Comment by fatihergin** [comment]
You can simply re-set the main nav controller's graph which hosts the all other tabs' graphs.

```
fun navigateFirstTabWithClearStack() {
        val navController = findNavController(R.id.nav_host_main)
        val navHostFragment: NavHostFragment = supportFragmentManager.findFragmentById(R.id.nav_host_main) as NavHostFragment
        val inflater = navHostFragment.navController.navInflater
        val graph = inflater.inflate(R.navigation.nav_graph_main)
        graph.startDestination = R.id.nav_graph_tab1

        navController.graph = graph
    }

```

**Comment by ngocmanh1609** [comment]
thank you @fatihergin , this is a very good alternative solution. The old solution take me more steps to clear all backstack and navigate to the first tab. <3 <3

**Comment by ngocmanh1609** [comment]
I can close issue now, thanks
