### ISSUE TITLE
Room Select Query always returns Null when wrapping with LiveData.

### ISSUE THREAD

**Issue by vikramKirubaharan** [android/architecture-components-samples#770]
Inserting the data is working properly. But when retrieving data e.g getTripList() : LiveData<List<Trip>> i always get null value i.e livedata.value is always null. 
But when I invoke it in this way i.e getTripList() : List<Trip> data is retrieved properly. Please help us to resolve this issue ASAP.

**Comment by ianhanniballake** [comment]
`livedata.value` will be null when you first get the `LiveData` - you have to `observe` it.
