### ISSUE TITLE
Can anybody explain why "setValue" function of "NetworkBoundResource" is restricted for use on Main Thread ? 

### ISSUE THREAD

**Issue by nidhi88** [android/architecture-components-samples#771]
`/*` 

	@MainThread
	private fun setValue(newValue: Resource<ResultType>) {
		if (result.value != newValue) {
			result.value = newValue
		}
	}

*/

We can use postValue and allow it to be modified on any thread, right

**Comment by ChillingVan** [comment]
This can help avoid operating View on background thread.

**Comment by ashdavies** [comment]
This is the design for `LiveData` as it's intended for a thread safe usage with views, it's not really designed as a threading replacement when there are so many other options available (Coroutines, RxJava).

However should you need to use `LiveData` off the main thread you can call `postValue` to schedule a `setValue`, be careful of this however as you can sometimes run into race conditions.

**Comment by ianhanniballake** [comment]
Yep, `LiveData` (and its subclasses like `MediatorLiveData`) require that you call `setValue` on the main thread.
