### ISSUE TITLE
Is that not a good practice for calling viewModel.observe() in onActivityCreated?

### ISSUE THREAD

**Issue by ChillingVan** [android/architecture-components-samples#772]
https://github.com/android/architecture-components-samples/blob/72183dfd43bd6311d4a3acae46560ebebc5098c0/BasicSample/app/src/main/java/com/example/android/persistence/ui/ProductFragment.java#L94

Under the new AndroidX Navigation framework:
When jumping from Fragment A to Fragment B, and back to A, the onActivityCreate() will be called again for Fragment A. If the viewModel is not created every time in onActivityCreate, then the liveData in viewModel will observe again and notifies more than one Observer.
Although for current sample this is fine, I think it is better that the observe should be in Fragment onCreate.

**Comment by hoc081098** [comment]
observe(viewLifecyclerOwner)

**Comment by ianhanniballake** [comment]
You should prefer `onCreateView()` or `onViewCreated()` over `onActivityCreated()`, but they're all called at the same time. All of them should be using `getViewLifecycleOwner()` and there's a Lint check in Fragments to enforce this in Fragment 1.2.0.

**Comment by ChillingVan** [comment]
https://proandroiddev.com/5-common-mistakes-when-using-architecture-components-403e9899f4cb

Thanks and this link may help.
