### ISSUE TITLE
MenuItemImpl checked behavior

### ISSUE THREAD

**Issue by firefinchdev** [android/architecture-components-samples#779]
In an activity, if I perform an operation like:
```kotlin
val subMenu = navigationView.menu.findItem(R.id.monitored_apps).subMenu
subMenu.clear()
for(...) {
    subMenu.add(groupId, 0, index, name).setChecked( getIsChecked(name) )
}
```
then after selecting an item from the navigation view does not respect android:checkableBehavior="single"

i.e. The item checked programatically in the above code remains checked even when choosing a different item from the navigation view.

The result is that after selecting some item, there are total two items checked in the navigation view.

**Comment by firefinchdev** [comment]
After that, if I go again to the navigation view and select some other item (other than the already two checked items), then there are total two items selected in the group, the programatically selected one, and the new item user has selected.

**Comment by firefinchdev** [comment]
However, after that if the user selects the original item (the item that is already checked programatically), then the android:checkableBehavior="single" behavior is restored.
Furthur selections now respects android:checkableBehavior="single"

**Comment by firefinchdev** [comment]
Expected behavior: 
android:checkableBehavior="single" should be respected when an item is checked programatically

**Comment by ianhanniballake** [comment]
This doesn't seem to be an issue with the samples. You can file an issue against Material Design Components (which owns NavigationView) on [their project](https://github.com/material-components/material-components-android/issues/new/choose) if you're still having an issue.
