### ISSUE TITLE
Why replace/remove instead of add/hide inside FragmentNavigator?

### ISSUE THREAD

**Issue by HeQuanLi** [android/architecture-components-samples#782]
question:Why replace/remove instead of add/hide inside FragmentNavigator?thank you

**Comment by DJDrama** [comment]
add hide can lead to memory leak i guess
you can make it work like add / hide by using viewmodels and that's why

**Comment by ianhanniballake** [comment]
See the [discussion on the issue tracker](https://issuetracker.google.com/issues/147251222).
