### ISSUE TITLE
NavigateUp() when popupToInclusive crash

### ISSUE THREAD

**Issue by axrkozlov** [android/architecture-components-samples#789]
In the Navigation Advanced Sample when using popup to inclusive like:

val navOptions = NavOptions.Builder()
                    .setPopUpTo(R.id.titleScreen,
                            true).build()
            findNavController().navigate(R.id.action_title_to_about,null,navOptions)

and then go back  from About fragment with:

findNavController().navigateUp()

have a crash 
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.android.navigationadvancedsample/com.example.android.navigationadvancedsample.MainActivity}: java.lang.IllegalStateException: unknown destination during deep link: com.example.android.navigationadvancedsample:id/home

It tries to recreate activity, why?

Thanks!

**Comment by nguyenvanminhfptpoly** [comment]
Do you have add Fragment in graph or add action ?

**Comment by ianhanniballake** [comment]
See [the issue on the issue tracker](https://issuetracker.google.com/issues/147378752), which was released in [Navigation 2.2.2](https://developer.android.com/jetpack/androidx/releases/navigation#2.2.2) and [Navigation 2.3.0-alpha05](https://developer.android.com/jetpack/androidx/releases/navigation#2.3.0-alpha05).
