### ISSUE TITLE
How can I run GithubBrowserSample on my Android studio?

### ISSUE THREAD

**Issue by chenriquevz** [android/architecture-components-samples#792]
Hello,

I am new to android developing in general and I am trying to run this famous, mentioned everywhere, GithubBrowserSample on my Android Studio, however I cannot clone it, only the whole repository, and when I do it, I still yet to find a way to proper build/run the project. Android studio simply doesnt recognize it as a module/runnable project.

Can anyone help me?

**Comment by ianhanniballake** [comment]
1) Check out the whole repository
2) In Android Studio, use File -> Open
3) Select the GithubBrowserSample directory

That'll open the GithubBrowserSample project itself.
