### ISSUE TITLE
GithubBrowserSample has potentially a useless misleading folder/directory

### ISSUE THREAD

**Issue by chenriquevz** [android/architecture-components-samples#794]
Hi,

I dont know if it is the right place to post it, but I think 'src/release' is doing nothing in the build.  As a new developer I was struggling to make "@OpenForTesting" work until I notice that this folder 'src/release' is probably forgotten in the build.

**Comment by ianhanniballake** [comment]
It isn't useless - it provides a no-op version of `@OpenForTesting`, providing an alternative implementation to the real implementation in the `debug` folder over at  `src/debug/java/com/android/example/github/testing/OpenForTesting.kt`.

This ensures that classes that are annotated as `@OpenForTesting` are not actually open (i.e., not annotated with `@OpenClass`) in release builds.

**Comment by chenriquevz** [comment]
> It isn't useless - it provides a no-op version of `@OpenForTesting`, providing an alternative implementation to the real implementation in the `debug` folder over at `src/debug/java/com/android/example/github/testing/OpenForTesting.kt`.
> 
> This ensures that classes that are annotated as `@OpenForTesting` are not actually open (i.e., not annotated with `@OpenClass`) in release builds.

Hi, Ian. Thank you for your clarifying it!
One thing that still concerns me here tho, , the `src/java/com/android/example/github/testing` is not a java folder, I cannot add files, packages, nothing. The only way I found to replicate what is done in the sample is to create a folder outside Android Studio and paste in the path that was project was on. Is that the right way to do it?!

Once again, thank you for your help!

**Comment by ianhanniballake** [comment]
Working fine here. Make sure your [selected build variant in Android Studio](https://developer.android.com/studio/run#changing-variant) is set to debug, which is what enables the `src/debug` directories as valid directories.

Note that the Android view makes this very apparent, having both the main source and the debug source as separate line items (right alongside `androidTest`, `test`, etc.)

**Comment by chenriquevz** [comment]
Ian, thank you very much. Newbie mistake. Lesson learned!! :)
