### ISSUE TITLE
Possible bug in NavigationBasicSample : bad traversal to leaderboard 

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [android/architecture-components-samples#796]
When I go to next screen, it's always the animation of moving the current content to the left.
However, after "42" and then "leaderboard", it uses the animation of moving content to the right, as if I pressed back.

Steps in the sample:

play
sign up
start
42
leaderboard

Is this intentional?

[2020-01-29_21-52-15.zip](https://github.com/android/architecture-components-samples/files/4130408/2020-01-29_21-52-15.zip)

**Comment by ianhanniballake** [comment]
Yes, it is supposed to be using the back animation.

**Comment by AndroidDeveloperLB** [comment]
So I go forward to a new screen that wasn't in the history, but there is a back animation?!
