### ISSUE TITLE
Question: for mimicing animation between Activities, is it possible to use their animation?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [android/architecture-components-samples#797]
I've noticed you set the animation by yourself in code (in the navigation file).
But this means that it doesn't follow the OS's animation between Activities, which isn't a nice thing...

Is it possible to use the one of the OS ?

**Comment by ianhanniballake** [comment]
No, and this is usually a terrible idea: activity animations are built with an opaque background in mind and using them with Fragments (which generally do not have an opaque background as that leads to overdraw) leads to [glitchy transitions](https://issuetracker.google.com/issues/145468417).

Also, the framework does not make its activity transitions public, so you'd have to copy them even if you did want to use them.

**Comment by AndroidDeveloperLB** [comment]
But if navigation framework is supposed to replace the multi-Activity navigation in apps, shouldn't it also mimic the transition between them?
It's weird that in some places of the app it will be one transition (between Activities) and in others it will be different (between fragments).
Even when you start an Activity of another app (startActivityForResult, for example), you will notice it...
