### ISSUE TITLE
[MaterialToolbar] setupWithNavController reset the navigationIcon

### ISSUE THREAD

**Issue by GiacomoPis** [android/architecture-components-samples#800]
Hi,
I'm working with Navigation Components and Material Components and I 

Using MaterialToolbar, NavigationController, AppBarConfiguration

in activity onCreate

```
mToolbar = toolbar as MaterialToolbar
mToolbar.setNavigationIcon(R.drawable.ic_chevron_sx_grey)

setSupportActionBar(mToolbar)

navController = findNavController(R.id.login_nav_host_fragment)
appBarConfiguration = AppBarConfiguration(setOf(
      R.id.fragmentSplash,
      R.id.fragmentLogin
))

mToolbar.setupWithNavController(navController, appBarConfiguration)
```

call to method 

`mToolbar.setupWithNavController(navController, appBarConfiguration)`

invalidate the setup of navigation icon

`mToolbar.setNavigationIcon(R.drawable.ic_chevron_sx_grey)
`

**Comment by nguyenvanminhfptpoly** [comment]
override fun onSupportNavigateUp(): Boolean {
        val navController = this.findNavController(R.id.nav_host_fragment)
        return  NavigationUI.navigateUp(navController, drawerLayout)
    }

try this, dude

**Comment by GiacomoPis** [comment]
The problem is not related to the up functionality, but it is related to the back icon customization
by calling
`mToolbar.setNavigationIcon(R.drawable.ic_chevron_sx_grey)`

The strange behavior is the following:

If I don't call
`mToolbar.setupWithNavController(navController, appBarConfiguration)`
my custom back icon appears correctly, if I call this method, the icon is reset to the default icon!

**Comment by ianhanniballake** [comment]
This doesn't seem to be an issue with the samples here, but an issue with Navigation and therefore should be filed on [the issue tracker](https://issuetracker.google.com/issues/new?component=409828).

In this specific case, custom back icons are not supported by NavigationUI, feel free to star [the existing issue](https://issuetracker.google.com/issues/121078028).
