### ISSUE TITLE
Unnecessary "product" ObservableField in BasicSample ProductViewModel

### ISSUE THREAD

**Issue by jrios6** [android/architecture-components-samples#802]
In ProductViewModel, there is an ObservableField<ProductEntity> and a LiveData<ProductEntity>. The UI is bound to the ObservableField, with the Fragment observing changes in LiveData and updating the ObservableField with the setProduct() method. 

Since the UI can be bound directly to the product LiveData, is there a need to have an additional ObservableField for the product? Wouldn't the two be holding copies of the same product object?

**Comment by jrios6** [comment]
From #34, I believe that LiveData used to not support DataBinding and there was a need for an ObservableField to bind product to the UI. However, with v1.0.0, we can simply bind the UI to LiveData and remove the need to observe LiveData within the fragment and updating changes to ObservableField?

**Comment by ianhanniballake** [comment]
Yep, the `ObservableField` is no longer needed.

The other important part is to make sure you call `setLifecycleOwner()` on the binding object so that DataBinding knows what `LifecycleOwner` to use to observe the `LiveData`.
