### ISSUE TITLE
LiveData is leaking when sharing ViewMode between two Fragments

### ISSUE THREAD

**Issue by bdushi** [android/architecture-components-samples#811]
LiveData is leaking when sharing ViewMode initialized using Navigation back stack,  between two Fragments or one Fragment and one Dialog. LiveData keeps previous observer when returned back, even though I observe using viewLifecycleOwner.

**Comment by ianhanniballake** [comment]
This isn't an issue with the samples here, so this isn't the right place for your issue.

Sounds like this is a good candidate for a [StackOverflow question](www.stackoverflow.com) that includes your code.

**Comment by bdushi** [comment]
https://issuetracker.google.com/issues/150888449
