### ISSUE TITLE
Navigation, Saving fragment state(Feature Request)

### ISSUE THREAD

**Issue by OleksandrGrument** [android/architecture-components-samples#813]
Asking you to add possibility not to recreate fragment each time, for example - to add possibility mark fragment as "recreatable" to define which fragments should recreate and which shouldn't

related issue - https://github.com/android/architecture-components-samples/issues/530

Many developers waiting for this possibility, don't ignore please.

**Comment by ianhanniballake** [comment]
Note that this is *not* the proper forum for feature requests - this is only for issues with the samples here (you'd want to file feature requests for libraries [on the issue tracker](https://issuetracker.google.com/)).

First of all, Fragments aren't destroyed or recreated when on the back stack.

Fragments already save and restore their View state when on the back stack. If you have a Fragment that:
1) Saves and restores its state over configuration changes
2) Saves and restores its state over process death (i.e., when using 'Don't keep activities')

But doesn't save its state when on the back stack, [file a bug against Fragments](https://issuetracker.google.com/issues/new?component=460964). If either case 1) or 2) fails, that's an issue with your Fragment that you need to fix first.
