### ISSUE TITLE
Writing Benchmark tests for recyclerview within an activity isn't working. Benchmark tests with custom views are not working as well.

### ISSUE THREAD

**Issue by thrlr123** [android/architecture-components-samples#817]
My Android project has library module (our own SDK code), app module. I added benchmark module as per the documentation(https://developer.android.com/studio/profile/benchmark#top_of_page). 

Here https://developer.android.com/studio/profile/benchmark#full-setup It said **Place code and resources you want to benchmark into a library module if they aren't already in one.**

Since, I already have Library module available, I just added as a dependency in my benchmark's `build.gradle` file.

And I followed this test in here 
https://github.com/android/architecture-components-samples/blob/master/PagingWithNetworkSample/benchmark/src/androidTest/java/com/example/benchmark/BenchmarkActivity.kt 

and wrote mine in java. However, when I run the code I am seeing an NPE happening in my activity's adapter's onBindViewHolder as getApplicationContext().getApplicationInfo() is null.

Here's my **RecyclerViewBenchmarkTest**:

```
@RunWith(AndroidJUnit4.class)
public class RecyclerViewBenchmarkTest {

    @Rule
    public BenchmarkRule benchmarkRule = new BenchmarkRule();

    @Rule
    public ActivityTestRule<DebugActivity> activityTestRule = new ActivityTestRule<>(DebugActivity.class);

    @UiThreadTest
    @Test
    public void scrollItem() {
        Activity activity = activityTestRule.getActivity();
        final BenchmarkState state = benchmarkRule.getState();
        RecyclerView recyclerView = activity.findViewById(R.id.clf_sections);
        assertNotNull(recyclerView);

        // If RecyclerView has children, the items are attached, bound, and gone through layout.
        // Ready to benchmark.
        assertTrue("RecyclerView expected to have children", recyclerView.getChildCount() > 0);

        while (state.keepRunning()) {
            scrollByOneItem(recyclerView);
        }
    }

    private void scrollByOneItem(@NotNull RecyclerView scrollByOneItem) {
        View view = scrollByOneItem.getChildAt(scrollByOneItem.getChildCount() - 1);
        Intrinsics.checkExpressionValueIsNotNull(view, "getChildAt(childCount - 1)");
        scrollByOneItem.scrollBy(0, view.getHeight());
    }
}
```

Crash:

```
java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String java.lang.CharSequence.toString()' on a null object reference
at com.abc.DebugActivity$DebugActivityAdapter.onBindViewHolder(DebugActivity.java:159)
```

**How to overcome this issue?** 

Also, are there any sample benchmark tests in java that explains how to access layouts from benchmark tests that has customViews? I wrote another BenchmarkTest, a simple one following the official documentation(https://developer.android.com/studio/profile/benchmark#write-benchmark), but I am having issues with it when using layouts with custom views, when not using custom view layouts it seems to work.

My **ViewBenchmark.java** code:

```
@RunWith(AndroidJUnit4.class)
public class ViewBenchmark {
    @Rule
    public BenchmarkRule benchmarkRule = new BenchmarkRule();

    @Test
    public void simpleViewInflate() {
        Context context = ApplicationProvider.getApplicationContext();
        final BenchmarkState state = benchmarkRule.getState();
        LayoutInflater inflater = LayoutInflater.from(context);
        FrameLayout root = new FrameLayout(context);

        while (state.keepRunning()) {
            inflater.inflate(R.layout.mr_map_view, root, false);
        }
    }
}
```

Issue:
```
android.view.InflateException: Binary XML file line #9 in com.abc.test:layout/mr_map_view: Binary XML file line #9 in com.abc.test:layout/mr_map_view: Error inflating class com.abc.maprender.GLTextureMapView
Caused by: android.view.InflateException: Binary XML file line #9 in com.abc.test:layout/mr_map_view: Error inflating class com.abc.maprender.GLTextureMapView
Caused by: java.lang.reflect.InvocationTargetException
```

**Comment by ianhanniballake** [comment]
This issue tracker is only for issues with these specific samples. If you are having issues with your own usage of Benchmarking, you should [ask a question on StackOverflow](https://stackoverflow.com/questions/tagged/androidx-benchmark) or [file an issue against Benchmarking](https://issuetracker.google.com/issues/new?component=585351).
