### ISSUE TITLE
NavController Add a navigation dynamically

### ISSUE THREAD

**Issue by Yinzeyu** [android/architecture-components-samples#823]
![image](https://user-images.githubusercontent.com/19818099/77993951-c276b880-735b-11ea-9ba0-be803b02087b.png)
You don't want to add another navigation through include. You want to add it dynamically
![MSKJH@5E8FYNX%25@$FGT0A](https://user-images.githubusercontent.com/19818099/77994181-24cfb900-735c-11ea-8f8e-6bfde310df18.png)
But the discovery will remove the original navgraph,
Is there any other way

**Comment by ianhanniballake** [comment]
This issue tracker is for issues with the samples in this project, not for general issues with the libraries seen in these samples. For that, you'd want to file issues against the libraries themselves, such as in the [Navigation component](https://issuetracker.google.com/issues/new?component=409828).
