### ISSUE TITLE
@Transaction with no parameters caues compile time error

### ISSUE THREAD

**Issue by farmazon3000** [android/architecture-components-samples#828]
I'm using room_version 2.2.5.

When I have transaction without params
```
@Transaction
fun theTrans() {
  // do sth
}
```
Then it's generated to
```
@Override
public void theTrans() {
  __db.beginTransaction();
  try {
    JustAnotherDaoInTheWall.DefaultImpls.theTrans(this, );
    __db.setTransactionSuccessful();
  } finally {
    __db.endTransaction();
  }
}
```
Please not the loose hanging ```,``` at the and of the longest line above.

**Comment by farmazon3000** [comment]
Changing to
```
@Transaction
fun theTrans(x:Any) {
  // do sth
}
```
workarounds this issue.

I need a nice real fix, not a workaround, though.

**Comment by ianhanniballake** [comment]
This issue tracker is for issues with the samples in this repository. You'll want to [file an issue against Room](https://issuetracker.google.com/issues/new?component=413107&template=1096568).
