### ISSUE TITLE
Updating an item, but next item will jumping [paging room]

### ISSUE THREAD

**Issue by wizos** [android/architecture-components-samples#829]
I use paging with Room to get get articles in my APP like `DataSource.Factory<Integer,Article> getArticles();`

When i updating an item ( the last item on current page), the next item(the first item on next page) will jumping, I found that it was because the next item got null with 'getitem()', is that a bug? How can I solve it, thank you.

**Comment by ianhanniballake** [comment]
This issue tracker is for issues with the samples in this repository. You'll want to [file an issue against Paging](https://issuetracker.google.com/issues/new?component=413106&template=1096385).
