### ISSUE TITLE
NetworkBoundResource#loadFromDb() on MainThread？？？

### ISSUE THREAD

**Issue by idealcn** [android/architecture-components-samples#842]
NetworkBoundResource#loadFromDb() on MainThread？？？why not io thread?

**Comment by malinkang** [comment]
https://developer.android.com/training/data-storage/room/accessing-data 
![image](https://user-images.githubusercontent.com/3365208/122740217-57920400-d2b6-11eb-926b-f8cff3c6148d.png)

**Comment by idealcn** [comment]
三克油
