### ISSUE TITLE
[BUG] PagingSample - Doesn't rebind null items

### ISSUE THREAD

**Issue by arduia** [android/architecture-components-samples#856]
After quick scrolling down on Recycler View, half of upper items show null value and doesn't rebind with data although PlaceHolders are enabled in Paging 3.

**Comment by dlam** [comment]
I believe this issue was inherently fixed as part of https://issuetracker.google.com/158763195, which now resends hints that are based on presenter state.

**Comment by dlam** [comment]
Although this sample doesn't filter, it should also fix this bug, which is relevant to the hint conflation logic + presenter state (both are fixed).

**Comment by arduia** [comment]
Thanks @dlam. Will check it out.
