### ISSUE TITLE
When I swipe up to load more pages, why it is refreshed effect ？？？

### ISSUE THREAD

**Issue by 8debug** [android/architecture-components-samples#880]
## PagingWithNetworkSample

When I swipe up to load more pages, it is refreshed

**Comment by Lesincs** [comment]
annotation following code in RedditActivity.kt will solve this bug:

>  lifecycleScope.launchWhenCreated {
            @OptIn(ExperimentalPagingApi::class, ExperimentalCoroutinesApi::class)
            adapter.dataRefreshFlow.collectLatest {
                list.scrollToPosition(0)
            }
        }

**Comment by dlam** [comment]
Woops - thanks for reporting this. Linked PR fixes this issue.
