### ISSUE TITLE
PagingWithNetworkSample : class not found  inside MainActivity.kt

### ISSUE THREAD

**Issue by mehtahardikr** [android/architecture-components-samples#890]
![Screen Shot 2020-08-12 at 3 54 26 PM](https://user-images.githubusercontent.com/12496655/90004979-29b25b00-dcb4-11ea-8f1c-d9ea33a239e7.png)
Class not found in followig path  `import com.android.example.paging.pagingwithnetwork.reddit.repository.RedditPostRepository`

**Comment by dlam** [comment]
This class is here: https://github.com/android/architecture-components-samples/blob/master/PagingWithNetworkSample/lib/src/main/java/com/android/example/paging/pagingwithnetwork/reddit/repository/RedditPostRepository.kt

It's in a separate module.
