### ISSUE TITLE
Same value was passed as the nextKey in two sequential Pages loaded from a PagingSource in Paging Library 3 Android

### ISSUE THREAD

**Issue by Aminul-Haque-Aome** [android/architecture-components-samples#901]
I migrated from paging 2 to paging 3. I tried to implement ItemKeyedDataSource of Paging 2 to Paging library 3. But the problem I was facing is, the same value(currentJodId) was passed as the nextkey in two sequential Pages loaded. And After that app crashes. but if I add "keyReuseSupported = true" in DataSource, app does not crash. But it started calling same item id as the nextkey.

check this https://stackoverflow.com/questions/63870064/same-value-was-passed-as-the-nextkey-in-two-sequential-pages-loaded-from-a-pagin

**Comment by dlam** [comment]
Issues here are intended for the samples - it looks like you've already posted on SO, so I'll just close this out.
