### ISSUE TITLE
Check Empty list / show empty view while using Paging3 lib.

### ISSUE THREAD

**Issue by phm1015** [android/architecture-components-samples#917]
I am using paging3 library in my project.

I am able to determine if refresh state is loading or error .
But i am not able to determine which condition to check if list is empty and i want to update my view accordingly and show empty view.

Can you please help me here?

**Comment by dlam** [comment]
Could you re-ask your question on [StackOverflow](https://stackoverflow.com/)? Happy to post a reply there, it's much more searchable for other users hitting the same issue. (And also this issue tracker is for issues with the samples themselves).

**Comment by dlam** [comment]
Feel free to drop a link to your question here, I'm watching this thread so will get a notification!

**Comment by phm1015** [comment]
i have asked on stackoverflow and link for same is
https://stackoverflow.com/questions/64370736/how-to-show-empty-view-while-using-android-paging-3-library
