### ISSUE TITLE
[PagingWithNetworkSample] network request was executed in main thread

### ISSUE THREAD

**Issue by 1step2hell** [android/architecture-components-samples#930]
redditApi.getTop()  was executed in main thread, both in PagingSource and RemoteMediator.

The [offical doc](https://developer.android.com/topic/libraries/architecture/paging/v3-network-db#implement-remotemediator) said that "Suspending network load via Retrofit. This doesn't need to be  wrapped in a withContext(Dispatcher.IO) { ... } block since Retrofit's Coroutine CallAdapter dispatches on a worker thread."  But it's not true! When you log out the thread name, you will find it's main thread. This is a very serious problem, might cause ANR, and I can't find a way make it execute in worker thread so far.

Please check is it a bug of Paging, or is there some advanced usage I don't know.

Also same problem [here](https://stackoverflow.com/questions/63985284/does-pagingdata-run-on-a-background-thread-by-default-in-paging-3-library)

**Comment by dlam** [comment]
In the SO post you linked, it clearly states that the suspending call adapter for Retrofit will dispatch on background thread for you. If this were not the case, Android would immediately throw a NetworkOnMainThreadException crashing the app.

To be clear, in a suspending function that makes a suspending network call via retrofit, only the network call is made on the background thread.. so you might end up with:

```
suspend fun load(..): .. {
    doStuff() // This will usually run on main thread by default
    retrofitCall() // This is automatically dispatched on Dispatchers.IO
    doMoreStuff() // This will usually run on main thread by default
}
```

A network call on main thread will definitely not produce an ANR, it will immediately crash the app.
