### ISSUE TITLE
There is no 'ForegroundInfo' class in 'androidx.work:work-runtime-ktx:2.2.0' version used by 'WorkManagerSample'.

### ISSUE THREAD

**Issue by hanjoongcho** [android/architecture-components-samples#941]
Good morning :)
There seems to be a problem with the work-runtime-ktx:2.2.0 version used by the WorkManagerSample project.
The 'ForegroundInfo' class is not loaded when using the 2.2.0 version defined in the versions.gradle file.
In version work-runtime-ktx:2.4.0 'ForegroundInfo' class loads well.

- work-runtime-ktx:2.2.0 

![image](https://user-images.githubusercontent.com/7098851/103048539-4c457080-45d2-11eb-91b8-6082d3651d62.png)

- work-runtime-ktx:2.4.0 

![image](https://user-images.githubusercontent.com/7098851/103048594-7d25a580-45d2-11eb-919f-f20d2e2e6a5f.png)

**Comment by duongquocphat** [comment]
@hanjoongcho I fixed this issue by updating to 2.4.0

**Comment by keyboardsurfer** [comment]
Fixed in main.
