### ISSUE TITLE
[ViewBinding] How to Ignore single view/viewgroup?

### ISSUE THREAD

**Issue by yizems** [android/architecture-components-samples#988]
How to ignore single view/viewgroup or viewgroup & his children? Whether the relevant configuration rules can be added? 

like this:

`viewbinding.ignore`

```
abc_**
**_abc
```

**Comment by jun-wu-tw** [comment]
```xml
<LinearLayout
        ...
        tools:viewBindingIgnore="true" >
    ...
</LinearLayout>
```
The official document introduced the way of ignoring the code generated by `ViewBinding`.
https://developer.android.com/topic/libraries/view-binding#setup

**Comment by yizems** [comment]
Too rough
