### ISSUE TITLE
Bug: as opposed to what was written, there is no sample here of using setExpedited

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [android/architecture-components-samples#996]
Reporting an issue with the Architecture Components or the samples?
Samples, and docs about them.

## Bug report or feature request for Architecture Components? 
Bug.

## Issue with the samples? 
Yes.

Please add the sample name ("all", "GithubBrowserSample", "BasicRxJavaSampleKotlin", etc.) and include it in the title if it applies.
WorkManagerMultiprocessSample , WorkManagerSample

The bug is that this is written on the docs:
https://developer.android.com/about/versions/12/foreground-services#recommended-alternative

> To see a complete example of how WorkManager 2.7.0 uses expedited jobs, look through the WorkManagerSample on GitHub.

But when I enter here, there is no mention of it anywhere here.
I also don't get what's the advantage of using it, and if it's at least as reliable as a foreground service. I requested to make it at least as reliable, and also wrote about this here:
https://issuetracker.google.com/issues/189497997
And since I have a lot of questions about this, wrote it here:
https://stackoverflow.com/q/67749284/878126

**Comment by calren** [comment]
Sorry for the confusion, it's on the `android-s` specific branch https://github.com/android/architecture-components-samples/tree/android-s. We'll be merging this branch into main once Android S is stable and released.

**Comment by AndroidDeveloperLB** [comment]
@calren Where should I look there?

**Comment by calren** [comment]
This commit might be helpful: https://github.com/android/architecture-components-samples/commits/android-s

**Comment by AndroidDeveloperLB** [comment]
@calren I don't understand. Which folder there to look at?
