### ISSUE TITLE
[Navigation Advanced Sample 2.4.0-alpha01] Wrong destination when back or arrow button clicked

### ISSUE THREAD

**Issue by DJDrama** [android/architecture-components-samples#997]
[Navigation Advanced Sample 2.4.0-alpha01]

When you click the "About" Button in "Home" Screen, and then click other tabs("Leaderboard" or "Register) and then click the back arrow or the back button, then the "Home Screen" Shows.

But actually the "About" screen should show in "Home" screen.

When you tap other tabs("Leaderboard" or "Register") and then come back to "Home" screen by tapping the "Home" tab, then the "About" screen shows.

**Comment by ianhanniballake** [comment]
As per [the issue filed on the official issue tracker](https://issuetracker.google.com/188963883), this is working as intended.
