### ISSUE TITLE
The 'kotlin-android-extensions' Gradle plugin is deprecated. Please use this migration guide (https://goo.gle/kotlin-android-extensions-deprecation) to start working with View Binding (https://developer.android.com/topic/libraries/view-binding) and the 'kotlin-parcelize' plugin.

### ISSUE THREAD

**Issue by OliverHoffmann** [android/architecture-components-samples#998]
I followed the ViewBindingSample but after inserting the line:

> apply plugin: 'kotlin-android-extensions'

in the file build.gradle the sync says:

> The 'kotlin-android-extensions' Gradle plugin is deprecated. 
> Please use this migration guide (https://goo.gle/kotlin-android-extensions-deprecation) to start working with View Binding (https://developer.android.com/topic/libraries/view-binding) and the 'kotlin-parcelize' plugin.

So either the warning or the sample is wrong and needs to be updated.

**Comment by zsmb13** [comment]
This error message is correct. The `kotlin-android-extensions` plugin is [deprecated and will be removed](https://android-developers.googleblog.com/2022/02/discontinuing-kotlin-synthetics-for-views.html), and you don't need to add it to use ViewBinding.
